import type { CaptureState, RecordingSession, CaptureDevice } from '../../shared/audio'
import type { JobRecord } from '../../shared/contracts'
import { invoke, serverRequest } from './platform'
let state:CaptureState={sessionId:'',memoId:'',state:'idle',elapsedMs:0,peak:0,rms:0,clipping:false,peaks:[],message:null}
let recorder:MediaRecorder|null=null, stream:MediaStream|null=null, context:AudioContext|null=null, timer:ReturnType<typeof setInterval>|undefined, began=0, recordingPath="", uploadQueue:Promise<void>=Promise.resolve(), uploadError:Error|null=null, queuedBytes=0, completion:Promise<CaptureState>|null=null
function emit():void{window.dispatchEvent(new CustomEvent('audio-capture',{detail:{...state}}))}
function cleanup():void{if(timer)clearInterval(timer);timer=undefined;stream?.getTracks().forEach(t=>t.stop());stream=null;void context?.close();context=null;recorder=null;recordingPath="";queuedBytes=0}
async function finish():Promise<CaptureState>{try{await uploadQueue;if(uploadError)throw uploadError;const path=recordingPath;const memo=await invoke<RecordingSession>('get_memo',{memoId:state.memoId});const jobId=await invoke<string>('import_memo_audio',{memoId:memo.id,expectedRevision:memo.revision,sourcePath:path,name:'Browser recording'});for(;;){const jobs=await invoke<JobRecord[]>('list_jobs');const job=jobs.find(j=>j.id===jobId);if(job?.status==='completed')break;if(job&&['failed','cancelled'].includes(job.status))throw new Error(job.message||'Recording could not be saved.');await new Promise(r=>setTimeout(r,250))}state={...state,state:'stopped',peak:0,rms:0,message:null}}catch(e){state={...state,state:'failed',message:e instanceof Error?e.message:String(e)}}finally{cleanup();emit()}return state}
export async function captureCommand(command:string,args:Record<string,unknown>):Promise<unknown>{
 if(command==='audio_capture_permission'){if(!navigator.mediaDevices?.getUserMedia)throw new Error('Microphone access requires HTTPS or localhost.');if(args.request){const test=await navigator.mediaDevices.getUserMedia({audio:true});test.getTracks().forEach(t=>t.stop())}return 'granted'}
 if(command==='audio_capture_devices'){const devices=await navigator.mediaDevices?.enumerateDevices();return (devices||[]).filter(d=>d.kind==='audioinput').map((d,i):CaptureDevice=>({id:d.deviceId,name:d.label||`Microphone ${i+1}`,isDefault:d.deviceId==='default'}))}
 if(command==='audio_capture_start'){
  if(recorder||completion)throw new Error('Finish the active recording first.')
  if(!navigator.mediaDevices?.getUserMedia)throw new Error('Microphone access requires HTTPS or localhost.')
  stream=await navigator.mediaDevices.getUserMedia({audio:args.deviceId?{deviceId:{exact:String(args.deviceId)}}:true})
  try{const mime=['audio/webm;codecs=opus','audio/mp4','audio/webm'].find(m=>MediaRecorder.isTypeSupported(m));recorder=new MediaRecorder(stream,mime?{mimeType:mime}:{});const name=(mime||'audio/webm').includes('mp4')?'recording.m4a':'recording.webm';const response=await serverRequest('/api/recording',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});recordingPath=(await response.json()).path;uploadQueue=Promise.resolve();uploadError=null;queuedBytes=0;began=Date.now();state={...state,sessionId:crypto.randomUUID(),memoId:String(args.memoId),state:'recording',elapsedMs:0,peaks:[],message:null};recorder.ondataavailable=e=>{if(!e.data.size||uploadError)return;const chunk=e.data;queuedBytes+=chunk.size;if(queuedBytes>8*1024*1024){uploadError=new Error('The connection cannot keep up with this recording. Please reconnect and record again.');void captureCommand('audio_capture_control',{action:'stop'});return}const path=recordingPath;uploadQueue=uploadQueue.then(async()=>{await serverRequest(`/api/recording?path=${encodeURIComponent(path)}`,{method:'PUT',body:chunk})}).catch(error=>{uploadError=error instanceof Error?error:new Error(String(error));void captureCommand('audio_capture_control',{action:'stop'})}).finally(()=>{queuedBytes-=chunk.size})};recorder.onerror=()=>{uploadError=new Error('The microphone recording stopped unexpectedly.');void captureCommand('audio_capture_control',{action:'stop'})};recorder.start(1000)
  context=new AudioContext();const analyser=context.createAnalyser();analyser.fftSize=512;context.createMediaStreamSource(stream).connect(analyser);const data=new Float32Array(analyser.fftSize)
  timer=setInterval(()=>{if(state.state!=='recording')return;analyser.getFloatTimeDomainData(data);const peak=Math.max(...data.map(Math.abs)),rms=Math.sqrt(data.reduce((n,x)=>n+x*x,0)/data.length);state={...state,elapsedMs:Date.now()-began,peak,rms,clipping:peak>.98,peaks:[...state.peaks.slice(-299),peak]};emit();if(state.elapsedMs>=2*60*60*1000)void captureCommand('audio_capture_control',{action:'stop'})},100);emit();return state
  }catch(e){cleanup();throw e}
 }
 const action=args.action
 if(action==='pause'&&recorder?.state==='recording'){recorder.pause();state={...state,state:'paused'};emit()}
 if(action==='resume'&&recorder?.state==='paused'){recorder.resume();began=Date.now()-state.elapsedMs;state={...state,state:'recording'};emit()}
 if(action==='stop'&&recorder){if(!completion){completion=new Promise<CaptureState>(resolve=>{recorder!.onstop=()=>{void finish().then(resolve)};recorder!.stop()}).finally(()=>{completion=null})}return completion}
 return state
}
