import { Checkbox, Select } from './components/StudioControls'
import { useEffect, useRef, useState } from 'react'
import { listen } from '@tauri-apps/api/event'
import { save } from '@tauri-apps/plugin-dialog'
import type { CaptureDevice, CaptureState, RecordingSession } from '../../shared/audio'
import type { ProjectSnapshot, SoundAsset, Voice } from '../../shared/contracts'
import { audioApi, processorApi } from './audioNative'
import { chooseAudio, errorMessage, isDesktop, systemApi, soundsApi, productionApi, projectApi } from './native'
import { AudioEditor } from './components/AudioEditor'
import { audioTime } from './components/AudioTransport'
export function VoiceMemosPage({ title = 'Voice Memos', project, onProjectChange }: { title?: string; project?: ProjectSnapshot; onProjectChange?: (project: ProjectSnapshot) => void }): JSX.Element {
 const [memos, setMemos] = useState<RecordingSession[]>([]), [selected, setSelected] = useState<string | null>(null), [devices, setDevices] = useState<CaptureDevice[]>([]), [device, setDevice] = useState(''), [capture, setCapture] = useState<CaptureState | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false), [query, setQuery] = useState(''), [trash, setTrash] = useState(false), [job, setJob] = useState<string | null>(null), [chapterId,setChapterId]=useState(''), [segmentId,setSegmentId]=useState(''), [sounds,setSounds]=useState<SoundAsset[]>([]), [soundId,setSoundId]=useState(''), [voices,setVoices]=useState<Voice[]>([]), [voiceId,setVoiceId]=useState('')
 const retake = useRef<{memoId:string;takeId:string;range:[number,number]} | null>(null), preparation = useRef(0), leadIn = useRef<HTMLAudioElement | null>(null)
 const [countdown,setCountdown] = useState('')
 useEffect(() => () => { preparation.current++; leadIn.current?.pause() }, [])
 async function startRetake(range:[number,number]):Promise<void> {
  if (!memo?.selectedTakeId) return
  const token=++preparation.current; retake.current={memoId:memo.id,takeId:memo.selectedTakeId,range};
  if(range[0]>0){setCountdown('Listen to the lead-in'); const player=new Audio(await audioApi.url(memo.id,memo.selectedTakeId)); leadIn.current=player; player.currentTime=Math.max(0,range[0]-2000)/1000; await player.play(); await new Promise(resolve=>window.setTimeout(resolve,Math.min(2000,range[0]))); player.pause();}
  for(let remaining=3;remaining>0;remaining--){if(token!==preparation.current)return;setCountdown(String(remaining));await new Promise(resolve=>window.setTimeout(resolve,1000));}
  if(token!==preparation.current)return;setCountdown('');setCapture(await audioApi.start(memo.id,device||null));
 }
 async function stopRecording():Promise<void>{
  const ended=await audioApi.control('stop');setCapture(ended);const replacement=retake.current;retake.current=null;
  if(replacement){let next=await audioApi.get(replacement.memoId);const recordedId=next.selectedTakeId;if(recordedId&&recordedId!==replacement.takeId){next=await audioApi.choose(next,replacement.takeId,'select');changed(next);setJob(await audioApi.replace(next,recordedId,replacement.range[0],replacement.range[1]));}}
  await reload();
 }
 const memo = memos.find(m => m.id === selected) || null, recording = capture?.state === 'recording' || capture?.state === 'paused'
 async function reload(): Promise<void> { if (!isDesktop()) return; setMemos(await audioApi.list(true)); setSounds(await soundsApi.list()); setVoices(await productionApi.voices()) }
 useEffect(() => { if (!isDesktop()) return; void reload().catch(e => setError(errorMessage(e))); void audioApi.control('status').then(setCapture).catch(()=>{}); void audioApi.devices().then(setDevices).catch(e => setError(errorMessage(e))); let cleanup: (() => void) | undefined; let mounted = true; void listen<CaptureState>('audio-capture', e => { if (!mounted) return; setCapture(e.payload); if (e.payload.state === 'stopped' || e.payload.state === 'failed') { void reload(); if (e.payload.message) setError(e.payload.message) } }).then(fn => { if (mounted) cleanup = fn; else fn() }); return () => { mounted = false; cleanup?.() } }, [])
 useEffect(() => { if (!job) return; const timer = window.setInterval(() => { void systemApi.jobs().then(records => { const record = records.find(r => r.id === job); if (record && ['completed','failed','cancelled'].includes(record.status)) { setJob(null); if (record.status !== 'completed') setError(record.message || record.status); void reload(); if(project && onProjectChange) void projectApi.open(project.rootPath).then(onProjectChange) } }).catch(e => setError(errorMessage(e))) }, 700); return () => window.clearInterval(timer) }, [job, project?.rootPath])
 function changed(next: RecordingSession): void { setMemos(items => items.map(m => m.id === next.id ? next : m)) }
 async function run(task: () => Promise<void>): Promise<void> { setError(''); setBusy(true); try { await task() } catch (e) { setError(errorMessage(e)) } finally { setBusy(false) } }
 return <div className="voice-memos"><header><h1>{title}</h1><p>Record, edit and compare takes. Your original recordings stay available.</p></header>{!isDesktop() && <p>Open the desktop app to record and manage your audio.</p>}{error && <div className="error-banner" role="alert">{error}</div>}
 <div className="audio-tools"><button disabled={busy || recording || !isDesktop()} onClick={() => void run(async () => { const m = await audioApi.create(`Memo ${new Date().toLocaleString()}`); setMemos(items => [m,...items]); setSelected(m.id); setTrash(false) })}>New memo</button><input aria-label="Search memos" placeholder="Search recordings" value={query} onChange={e => setQuery(e.target.value)} /><label><Checkbox checked={trash} onChange={e => setTrash(e.target.checked)} />Recently deleted</label></div>
 <div className="memo-layout"><aside>{memos.filter(m => m.deleted === trash && `${m.name} ${m.notes}`.toLowerCase().includes(query.toLowerCase())).map(m => <button className={m.id === selected ? 'selected' : ''} key={m.id} onClick={() => setSelected(m.id)}><strong>{m.favorite ? '★ ' : ''}{m.name}</strong><small>{new Date(m.updatedAtMs).toLocaleDateString()} · {m.takes.length} takes</small></button>)}</aside><main>{memo ? <><div className="audio-tools"><input aria-label="Memo name" key={memo.id + memo.revision} defaultValue={memo.name} onBlur={e => { if (e.target.value !== memo.name) void run(async () => changed(await audioApi.update({...memo,name:e.target.value}))) }} /><button disabled={busy} onClick={() => void run(async () => changed(await audioApi.update({...memo,favorite:!memo.favorite})))}>{memo.favorite ? 'Unfavorite' : 'Favorite'}</button><button disabled={recording || busy} onClick={() => void run(async () => changed(await audioApi.update({...memo,deleted:!memo.deleted})))}>{memo.deleted ? 'Restore' : 'Delete'}</button></div>
 <textarea aria-label="Memo notes" placeholder="Notes" key={'notes' + memo.id + memo.revision} defaultValue={memo.notes} onBlur={e => { if (e.target.value !== memo.notes) void run(async () => changed(await audioApi.update({...memo,notes:e.target.value}))) }} />
 {!memo.deleted && <><div className="audio-tools"><Select aria-label="Microphone" disabled={recording} value={device} onChange={e => setDevice(e.target.value)}><option value="">Default microphone</option>{devices.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</Select><button disabled={busy || recording || !!job} onClick={() => void run(async () => setCapture(await audioApi.start(memo.id,device || null)))}>Record</button><button disabled={busy || !recording} onClick={() => void run(async () => setCapture(await audioApi.control(capture?.state === 'paused' ? 'resume' : 'pause')))}>{capture?.state === 'paused' ? 'Resume' : 'Pause'}</button><button disabled={busy || !recording} onClick={() => void run(async () => { await stopRecording() })}>Stop & save</button><button disabled={busy || !recording} onClick={() => void run(async () => { retake.current=null; setCapture(await audioApi.control('discard')) })}>Discard</button><button disabled={busy || recording || !!job} onClick={() => void run(async () => { const source = await chooseAudio(); if (source) setJob(await audioApi.import(memo,source)) })}>Import audio</button></div>
 {capture?.memoId === memo.id && <div className="capture-meter" aria-live="polite"><span>{capture.state} · {audioTime(capture.elapsedMs)}</span><meter min={0} max={1} value={capture.rms} aria-label="Microphone level" />{capture.clipping && <strong>Clipping — lower microphone gain</strong>}</div>}
 {countdown && <p role="status">{countdown} <button onClick={()=>{preparation.current++;leadIn.current?.pause();retake.current=null;setCountdown('')}}>Cancel countdown</button></p>}
 {job && <p role="status">Processing audio… <button onClick={() => void systemApi.controlJob(job,'cancel')}>Cancel</button></p>}
 <AudioEditor onRecordRange={range=>void run(async()=>{try{await startRetake(range)}catch(error){retake.current=null;throw error}finally{setCountdown('')}})} memo={memo} onChange={changed} onQueued={setJob} disabled={busy || !!job || !!recording} />
 <details><summary>Use audio in books, clips & voices</summary><div className="audio-tools"><button disabled={busy||!!job||recording||!memo.selectedTakeId} onClick={()=>void run(async()=>setJob(await processorApi.publish(memo,'sound')))}>Send accepted audio to Sound Library</button><Select aria-label="Sound clip to edit" value={soundId} onChange={e=>setSoundId(e.target.value)}><option value="">Choose a library clip</option>{sounds.map(a=><option value={a.id} key={a.id}>{a.prompt}</option>)}</Select><button disabled={busy||!!job||recording||!soundId} onClick={()=>void run(async()=>setJob(await processorApi.importLibrary(memo,'sound',{soundId})))}>Import clip for editing</button></div>
 {project&&<div className="audio-tools"><Select aria-label="Book chapter" value={chapterId} onChange={e=>{setChapterId(e.target.value);setSegmentId('')}}><option value="">Choose a chapter</option>{project.chapters.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</Select><Select aria-label="Narration section" value={segmentId} onChange={e=>setSegmentId(e.target.value)}><option value="">Whole chapter</option>{project.chapters.find(c=>c.id===chapterId)?.segments.map((seg,i)=><option key={seg.id} value={seg.id}>Section {i+1}: {seg.text.slice(0,50)}</option>)}</Select><button disabled={busy||!!job||recording||!chapterId||!memo.selectedTakeId} onClick={()=>void run(async()=>setJob(await processorApi.publish(memo,segmentId?'segment':'chapter',{rootPath:project.rootPath,projectRevision:project.revision,chapterId,segmentId:segmentId||null})))}>Use accepted audio in book</button><button disabled={busy||!!job||recording||!chapterId} onClick={()=>void run(async()=>setJob(await processorApi.importLibrary(memo,'chapter',{rootPath:project.rootPath,chapterId})))}>Import chapter for editing</button></div>}
 <div className="audio-tools"><Select aria-label="Chatterbox voice" value={voiceId} onChange={e=>setVoiceId(e.target.value)}><option value="">Choose a custom narrator</option>{voices.filter(v=>!v.builtIn).map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</Select><button disabled={busy||!!job||recording||!voiceId||!memo.selectedTakeId} onClick={()=>void run(async()=>setJob(await processorApi.publish(memo,'voice',{voiceId})))}>Save as Chatterbox sample (6–20s)</button></div></details><button disabled={busy || !!job || recording || !memo.selectedTakeId} onClick={() => void run(async () => { const output = await save({title:'Export recording',defaultPath:`${memo.name}.wav`,filters:[{name:'Audio',extensions:['wav','flac','m4a','mp3']}]}); if (output) setJob(await audioApi.export(memo,output)) })}>Export selected audio</button></>}
 </> : <p>Select a memo or create your first recording.</p>}</main></div></div>
}
