import {StudioIcon} from './components/StudioIcon'
import {useToast,notify} from './components/StudioToast'
import { useOptionalWaveStudio } from './WaveStudioProvider'
import { Checkbox, Select } from './components/StudioControls'
import { useEffect, useRef, useState } from 'react'
import { listen } from './platform'
import { save } from './platform'
import type { CaptureDevice, CaptureState, RecordingSession } from '../../shared/audio'
import type { ProjectSnapshot, SoundAsset, Voice } from '../../shared/contracts'
import { audioApi, processorApi } from './audioNative'
import { chooseAudio, errorMessage, hasBackend, systemApi, soundsApi, productionApi, projectApi } from './native'
import { AudioEditor } from './components/AudioEditor'
import { audioTime } from './components/AudioTransport'
export function VoiceMemosPage({ title = 'Voice Memos', project, onProjectChange }: { title?: string; project?: ProjectSnapshot; onProjectChange?: (project: ProjectSnapshot) => void }): JSX.Element {
 const wave = useOptionalWaveStudio()
 const [memos, setMemos] = useState<RecordingSession[]>([]), [selected, setSelected] = useState<string | null>(null), [devices, setDevices] = useState<CaptureDevice[]>([]), [device, setDevice] = useState(''), [capture, setCapture] = useState<CaptureState | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false), [query, setQuery] = useState(''), [trash, setTrash] = useState(false), [job, setJob] = useState<string | null>(null), [chapterId,setChapterId]=useState(''), [segmentId,setSegmentId]=useState(''), [sounds,setSounds]=useState<SoundAsset[]>([]), [soundId,setSoundId]=useState(''), [voices,setVoices]=useState<Voice[]>([]), [voiceId,setVoiceId]=useState('')
 const retake = useRef<{memoId:string;takeId:string;range:[number,number]} | null>(null), preparation = useRef(0), leadIn = useRef<HTMLAudioElement | null>(null)
 const [countdown,setCountdown] = useState('')
 const [checked,setChecked]=useState<string[]>([]),[levels,setLevels]=useState<number[]>([])
 useToast(error,'error')
 useEffect(()=>{if(!capture)return;if(capture.state==='recording')setLevels(v=>[...v.slice(-79),Math.max(0,Math.min(100,(60+20*Math.log10(Math.max(0.000001,capture.rms)))/60*100))]);else if(capture.state==='stopped'||capture.state==='failed')setLevels([])},[capture?.elapsedMs,capture?.state,capture?.memoId])
 useEffect(() => () => { preparation.current++; leadIn.current?.pause() }, [])
 async function startRetake(range:[number,number]):Promise<void> {
  if (!memo?.selectedTakeId) return
  const token=++preparation.current; retake.current={memoId:memo.id,takeId:memo.selectedTakeId,range};
  if(range[0]>0){setCountdown('Listen to the lead-in'); const player=new Audio(await audioApi.url(memo.id,memo.selectedTakeId)); leadIn.current=player; player.currentTime=Math.max(0,range[0]-2000)/1000; await player.play(); await new Promise(resolve=>window.setTimeout(resolve,Math.min(2000,range[0]))); player.pause();}
  for(let remaining=3;remaining>0;remaining--){if(token!==preparation.current)return;setCountdown(String(remaining));await new Promise(resolve=>window.setTimeout(resolve,1000));}
  if(token!==preparation.current)return;setCountdown('');setCapture(await audioApi.start(memo.id,device||null));
 }
 async function stopRecording():Promise<void>{
  const ended=await audioApi.control('stop');setCapture(ended);const replacement=retake.current;retake.current=null;
  if(replacement){let next=await audioApi.get(replacement.memoId);const recordedId=next.selectedTakeId;if(recordedId&&recordedId!==replacement.takeId){next=await audioApi.choose(next,replacement.takeId,'select');changed(next);setJob(await audioApi.replace(next,recordedId,replacement.range[0],replacement.range[1]));}}
  await reload();
 }
 const memo = memos.find(m => m.id === selected) || null, recording = capture?.state === 'recording' || capture?.state === 'paused'
 async function reload(): Promise<void> { if (!hasBackend()) return; setMemos(await audioApi.list(true)); setSounds(await soundsApi.list()); setVoices(await productionApi.voices()) }
 useEffect(() => { if (!hasBackend()) return; void reload().catch(e => setError(errorMessage(e))); void audioApi.control('status').then(setCapture).catch(()=>{}); void audioApi.devices().then(setDevices).catch(e => setError(errorMessage(e))); let cleanup: (() => void) | undefined; let mounted = true; void listen<CaptureState>('audio-capture', e => { if (!mounted) return; setCapture(e.payload); if (e.payload.state === 'stopped' || e.payload.state === 'failed') { void reload().catch(e=>setError(errorMessage(e))); if (e.payload.message) setError(e.payload.message) } }).then(fn => { if (mounted) cleanup = fn; else fn() }); return () => { mounted = false; cleanup?.() } }, [])
 useEffect(() => { if (!job) return; const timer = window.setInterval(() => { void systemApi.jobs().then(records => { const record = records.find(r => r.id === job); if (record && ['completed','failed','cancelled'].includes(record.status)) { setJob(null); if (record.status !== 'completed') setError(record.message || record.status); void reload(); if(project && onProjectChange) void projectApi.open(project.rootPath).then(onProjectChange) } }).catch(e => setError(errorMessage(e))) }, 700); return () => window.clearInterval(timer) }, [job, project?.rootPath])
 function changed(next: RecordingSession): void { setMemos(items => items.map(m => m.id === next.id ? next : m)) }
 async function run(task: () => Promise<void>): Promise<void> { setError(''); setBusy(true); try { await task() } catch (e) { setError(errorMessage(e)) } finally { setBusy(false) } }
 const shown=memos.filter(m=>m.deleted===trash && `${m.name} ${m.notes}`.toLowerCase().includes(query.toLowerCase()))
 const selectedMemos=checked.filter(id=>shown.some(m=>m.id===id))
 async function newMemo(record=false):Promise<void>{const next=await audioApi.create(`Voice memo ${new Date().toLocaleString()}`);setMemos(v=>[next,...v]);setSelected(next.id);setTrash(false);if(record){setLevels([]);setCapture(await audioApi.start(next.id,device||null))}}
 async function removeSelected():Promise<void>{for(const id of selectedMemos){if(recording&&capture?.memoId===id)continue;const latest=await audioApi.get(id);changed(await audioApi.update({...latest,deleted:!trash}))}setChecked([]);notify(trash?'Selected memos restored.':'Selected memos moved to recently deleted.')}
 return <div className="voice-memos"><header className="memo-header"><div className="memo-heading"><span className="screen-icon"><StudioIcon name="voice-memos"/></span><div><h1>{title}</h1><p>Record, edit and compare takes. Your original recordings stay available.</p></div></div><div className="audio-tools"><button disabled={busy||recording||!hasBackend()} onClick={()=>void run(()=>newMemo())}>+ New memo</button><button className="primary" disabled={busy||recording||!hasBackend()} onClick={()=>void run(()=>newMemo(true))}>Record new memo</button></div></header>
 {!hasBackend()&&<p>Open Homer Studio to record and manage your audio.</p>}
 <div className="memo-layout"><aside className="memo-library"><input type="search" aria-label="Search memos" placeholder="Search recordings" value={query} onChange={e=>setQuery(e.target.value)}/><label className="memo-trash"><Checkbox checked={trash} onChange={e=>{setTrash(e.target.checked);setChecked([]);setSelected(null)}}/>Recently deleted</label><div className="memo-list-heading"><small>RECORDINGS</small><button onClick={()=>setChecked(selectedMemos.length===shown.length?[]:shown.map(m=>m.id))}>{selectedMemos.length?'Clear':'Select all'}</button></div><div className="memo-recordings">{shown.map(m=><div className={`memo-row ${m.id===selected?'selected':''}`} key={m.id}><input type="checkbox" className="studio-checkbox" aria-label={`Select ${m.name}`} checked={checked.includes(m.id)} onChange={e=>setChecked(ids=>e.target.checked?[...ids,m.id]:ids.filter(id=>id!==m.id))}/><button className="memo-open" onClick={()=>setSelected(m.id)}><strong>{m.favorite?'Favorite / ':''}{m.name}</strong><small>{new Date(m.updatedAtMs).toLocaleDateString()} / {m.takes.length} takes</small></button></div>)}</div><footer><span>{selectedMemos.length} selected</span><button className="danger" disabled={busy||!selectedMemos.length||selectedMemos.some(id=>recording&&capture?.memoId===id)} title={selectedMemos.some(id=>recording&&capture?.memoId===id)?'Stop and save the active recording before deleting it.':undefined} onClick={()=>void run(removeSelected)}>{trash?'Restore selected':'Delete selected'}</button></footer></aside><main>{memo ? <><div className="audio-tools"><input aria-label="Memo name" key={memo.id + memo.revision} defaultValue={memo.name} onBlur={e => { if (e.target.value !== memo.name) void run(async () => changed(await audioApi.update({...memo,name:e.target.value}))) }} /><button disabled={busy} onClick={() => void run(async () => changed(await audioApi.update({...memo,favorite:!memo.favorite})))}>{memo.favorite ? 'Unfavorite' : 'Favorite'}</button><button disabled={busy || (recording && capture?.memoId === memo.id)} title={recording && capture?.memoId === memo.id ? 'Stop and save this recording before deleting it.' : undefined} onClick={() => void run(async () => changed(await audioApi.update({...await audioApi.get(memo.id),deleted:!memo.deleted})))}>{memo.deleted ? 'Restore' : 'Delete'}</button></div>
 <textarea className="memo-notes" aria-label="Memo notes" placeholder="Notes" key={'notes' + memo.id + memo.revision} defaultValue={memo.notes} onBlur={e => { if (e.target.value !== memo.notes) void run(async () => changed(await audioApi.update({...memo,notes:e.target.value}))) }} />
 {!memo.deleted && <><div className="audio-tools"><Select aria-label="Microphone" disabled={recording} value={device} onChange={e => setDevice(e.target.value)}><option value="">Default microphone</option>{devices.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</Select><button disabled={busy || recording || !!job} onClick={() => void run(async () => setCapture(await audioApi.start(memo.id,device || null)))}>Record</button><button disabled={busy || !recording} onClick={() => void run(async () => setCapture(await audioApi.control(capture?.state === 'paused' ? 'resume' : 'pause')))}>{capture?.state === 'paused' ? 'Resume' : 'Pause'}</button><button disabled={busy || !recording} onClick={() => void run(async () => { await stopRecording() })}>Stop & save</button><button disabled={busy || !recording} onClick={() => void run(async () => { retake.current=null; setCapture(await audioApi.control('discard')) })}>Discard</button><button disabled={busy || recording || !!job} onClick={() => void run(async () => { const source = await chooseAudio(); if (source) setJob(await audioApi.import(memo,source)) })}>Import audio</button></div>
 {capture?.memoId===memo.id&&recording&&<section className="live-recording" aria-label="Live microphone level"><div className="live-levels" aria-hidden="true">{levels.map((level,i)=><i key={i} style={{height:`${Math.max(2,level)}%`}}/>)}</div><div className="capture-meter"><span>{capture.state} / {audioTime(capture.elapsedMs)}</span><meter min={0} max={100} value={levels.at(-1)||0} aria-label="Microphone sound level"/><span>{capture.rms>0?`${Math.round(20*Math.log10(capture.rms))} dB`:'Quiet'}</span>{capture.clipping&&<strong>Clipping - lower microphone gain</strong>}</div></section>}
 {countdown && <p role="status">{countdown} <button onClick={()=>{preparation.current++;leadIn.current?.pause();retake.current=null;setCountdown('')}}>Cancel countdown</button></p>}
 {job && <p role="status">Processing audio... <button onClick={() => void systemApi.controlJob(job,'cancel')}>Cancel</button></p>}
 <AudioEditor onRecordRange={range=>void run(async()=>{try{await startRetake(range)}catch(error){retake.current=null;throw error}finally{setCountdown('')}})} memo={memo} onChange={changed} onQueued={setJob} disabled={busy || !!job || !!recording} />
 <details><summary>Use audio in books, clips & voices</summary><div className="audio-tools"><button disabled={busy||!!job||recording||!memo.selectedTakeId} onClick={()=>void run(async()=>setJob(await processorApi.publish(memo,'sound')))}>Send accepted audio to Sound Library</button><Select aria-label="Sound clip to edit" value={soundId} onChange={e=>setSoundId(e.target.value)}><option value="">Choose a library clip</option>{sounds.map(a=><option value={a.id} key={a.id}>{a.prompt}</option>)}</Select><button disabled={busy||!!job||recording||!soundId} onClick={()=>void run(async()=>setJob(await processorApi.importLibrary(memo,'sound',{soundId})))}>Import clip for editing</button></div>
 {project&&<div className="audio-tools"><Select aria-label="Book chapter" value={chapterId} onChange={e=>{setChapterId(e.target.value);setSegmentId('')}}><option value="">Choose a chapter</option>{project.chapters.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</Select><Select aria-label="Narration section" value={segmentId} onChange={e=>setSegmentId(e.target.value)}><option value="">Whole chapter</option>{project.chapters.find(c=>c.id===chapterId)?.segments.map((seg,i)=><option key={seg.id} value={seg.id}>Section {i+1}: {seg.text.slice(0,50)}</option>)}</Select><button disabled={busy||!!job||recording||!chapterId||!memo.selectedTakeId} onClick={()=>void run(async()=>setJob(await processorApi.publish(memo,segmentId?'segment':'chapter',{rootPath:project.rootPath,projectRevision:project.revision,chapterId,segmentId:segmentId||null})))}>Use accepted audio in book</button><button disabled={busy||!!job||recording||!chapterId} onClick={()=>void run(async()=>setJob(await processorApi.importLibrary(memo,'chapter',{rootPath:project.rootPath,chapterId})))}>Import chapter for editing</button></div>}
 <div className="audio-tools"><Select aria-label="Chatterbox voice" value={voiceId} onChange={e=>setVoiceId(e.target.value)}><option value="">Choose a custom narrator</option>{voices.filter(v=>!v.builtIn).map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</Select><button disabled={busy||!!job||recording||!voiceId||!memo.selectedTakeId} onClick={()=>void run(async()=>setJob(await processorApi.publish(memo,'voice',{voiceId})))}>Save as Chatterbox sample (6-20s)</button></div></details><div className="audio-tools memo-export-actions">{wave && <button disabled={busy || !!job || recording || !memo.selectedTakeId} onClick={() => void wave.importAudio('memo', memo.id)}>Open in Wave Studio</button>}<button disabled={busy || !!job || recording || !memo.selectedTakeId} onClick={() => void run(async () => { const output = await save({title:'Export recording',defaultPath:`${memo.name}.wav`,filters:[{name:'Audio',extensions:['wav','flac','m4a','mp3']}]}); if (output) setJob(await audioApi.export(memo,output)) })}>Export selected audio</button></div></>}
 </> : <div className="memo-empty"><StudioIcon name="microphone" width="48" height="48"/><h2>No recording selected</h2><p>Record a new memo or choose one from the list.</p><div className="audio-tools"><button disabled={busy||recording||!hasBackend()} onClick={()=>void run(()=>newMemo())}>+ New memo</button><button className="primary" disabled={busy||recording||!hasBackend()} onClick={()=>void run(()=>newMemo(true))}>Record new memo</button></div></div>}</main></div></div>
}
