import { isDesktop, uploadFile } from './platform'
import { NeutralSlider } from './components/NeutralSlider'
import { useEffect, useRef, useState } from 'react'
import { getCurrentWebview } from '@tauri-apps/api/webview'
import { open } from './platform'
import type { Voice, JobRecord } from '../../shared/contracts'
import type { RouteId } from '../../shared/navigation'
import { sourceClip, clipEnd, voiceColor, voiceAudioKey, formatWaveTime, timelineDuration, projectDuration } from '../../shared/waveStudio'
import { joinCandidateIds, replaceRange, assignVoice, changeSpeed, insertSilence, removeRange, splitAt } from '../../shared/waveStudioEdits'
import { useWaveStudio } from './WaveStudioProvider'
import { useWaveStudioPlayback } from './useWaveStudioPlayback'
import { errorMessage, hasBackend, productionApi, systemApi } from './native'
import { waveApi } from './waveStudioNative'
import { WaveStudioToolbar } from './components/WaveStudioToolbar'
import { WaveStudioTimeline } from './components/WaveStudioTimeline'
import { WaveStudioInspector } from './components/WaveStudioInspector'
import { WaveStudioLibraryDrawer } from './components/WaveStudioLibraryDrawer'
import { WaveRecordingPanel } from './components/WaveRecordingPanel'
import { WaveExportPanel } from './components/WaveExportPanel'
import { WaveProjectsPanel } from './components/WaveProjectsPanel'
import { WaveVideoReference } from './components/WaveVideoReference'
import { WaveProductionPanel } from './components/WaveProductionPanel'
function readRecentVoices(): string[] { try { const value: unknown=JSON.parse(localStorage.getItem('homer.wave.recentVoices') || '[]'); return Array.isArray(value) ? value.filter((id): id is string=>typeof id==='string') : [] } catch { return [] } }
export function WaveStudioPage({ onNavigate }: { onNavigate: (route: RouteId) => void }): JSX.Element {
 const w = useWaveStudio(), [drawer, setDrawer] = useState(false), [voices, setVoices] = useState<Voice[]>([]), [voiceMenu, setVoiceMenu] = useState(false), [speedMenu, setSpeedMenu] = useState(false), [silenceMenu, setSilenceMenu] = useState(false), [silence, setSilence] = useState(500), [customSpeed, setCustomSpeed] = useState(1), [pendingImport, setPendingImport] = useState<string | null>(null), [projects, setProjects] = useState(false), [exportPanel,setExportPanel]=useState(false), [job, setJob] = useState<JobRecord | null>(null), [jobId, setJobId] = useState('')
 const [recordPanel,setRecordPanel]=useState(false),[productionKind,setProductionKind]=useState<'speech'|'voices'|null>(null),[joining,setJoining]=useState(false),[importAt,setImportAt]=useState(0),[productionRegion,setProductionRegion]=useState<string|undefined>()
 const [help,setHelp]=useState(false),[joinChoices,setJoinChoices]=useState<string[]|null>(null)
 const [activeJobs,setActiveJobs]=useState<JobRecord[]>([])
 useEffect(()=>{if(!hasBackend())return;let alive=true;const poll=()=>{void systemApi.jobs().then(jobs=>{if(alive)setActiveJobs(jobs.filter(j=>j.kind==='wave_processing'&&['queued','running'].includes(j.status)))}).catch(()=>{})};poll();const timer=window.setInterval(poll,700);return()=>{alive=false;window.clearInterval(timer)}},[])
 const latest=useRef(w);latest.current=w
 async function openProduction(kind:'record'|'speech'|'voices'):Promise<void>{playback.stop();if(!w.project)await w.create();if(kind==='record')setRecordPanel(true);else {setProductionRegion(undefined);setProductionKind(kind)}}
 async function join(choice?:string|null):Promise<void>{if(!w.project)return;const p=w.project, ids=joinCandidateIds(p.timeline,w.view.selection,w.view.playheadMs,w.view.selectedId,w.view.selectedIds);if(ids.length<2){w.setError('Select at least two adjacent narration clips, or select a clip and its next neighbour.');return}const selected=p.timeline.clips.filter(c=>ids.includes(c.id)),a=Math.min(...selected.map(c=>c.startMs)),b=Math.max(...selected.map(clipEnd)),regions=p.timeline.voices.filter(v=>v.startMs<b&&v.endMs>a),tags=[...new Set(regions.map(v=>v.voiceId))];if(choice===undefined&&(tags.length>1||(tags.length===1&&regions.reduce((n,v)=>n+Math.min(b,v.endMs)-Math.max(a,v.startMs),0)<b-a))){setJoinChoices(tags);return}setJoinChoices(null);setJoining(true);playback.stop();try{const source=await waveApi.join(p,ids);if(latest.current.project?.id!==p.id||JSON.stringify(latest.current.project.timeline)!==JSON.stringify(p.timeline))throw new Error('Project changed during Join. Retry with the current selection.');const clips=p.timeline.clips.filter(c=>ids.includes(c.id)),start=Math.min(...clips.map(c=>c.startMs)),end=Math.max(...clips.map(clipEnd)),clip=sourceClip(source,start);clip.sourceEndMs=end-start;const joined=replaceRange(p.timeline,start,end,clip);const chosen=choice===undefined?tags[0]:choice;const voice=voices.find(v=>v.id===chosen);if(voice)joined.voices=assignVoice(joined,start,end,voice).voices;else joined.voices=joined.voices.flatMap(v=>v.endMs<=start||v.startMs>=end?[v]:[...(v.startMs<start?[{...v,endMs:start,production:undefined}]:[]),...(v.endMs>end?[{...v,startMs:end,production:undefined}]:[])]);w.edit(joined,[...p.sources,source]);w.setView(v=>({...v,selection:[start,end],selectedId:clip.id,selectedIds:[clip.id]}))}catch(e){w.setError(errorMessage(e))}finally{setJoining(false)}}
 const duration = w.project ? projectDuration(w.project) : 0
 const changedSelectionDuration = w.project && w.view.selection ? w.view.selection[1]-w.view.selection[0]+timelineDuration(changeSpeed(w.project.timeline,...w.view.selection,customSpeed))-timelineDuration(w.project.timeline) : 0
 useEffect(() => { if (!w.project || !voices.length) return; let changed=false; const regions=w.project.timeline.voices.map(r => { const v=voices.find(v=>v.id===r.voiceId); if (!v || (r.name===v.name && r.color===(voiceColor(v)))) return r; changed=true; return {...r,name:v.name,color:voiceColor(v)} }); if(changed) w.edit({...w.project.timeline,voices:regions}) }, [voices])
 const playback = useWaveStudioPlayback(w.project, ms => w.setView(v => ({ ...v, playheadMs: ms })), w.setError)
 useEffect(() => { if (hasBackend()) void productionApi.voices().then(setVoices).catch(e => w.setError(errorMessage(e))) }, [])
 useEffect(() => { if (!jobId || ['completed', 'failed', 'cancelled'].includes(job?.status || '')) return; const poll = () => { void systemApi.jobs().then(jobs => { const found = jobs.find(j => j.id === jobId); if (found) { setJob(found); if (found.status === 'failed') w.setError(found.message || 'Export failed') } }).catch(e => w.setError(errorMessage(e))) }; poll(); const timer = window.setInterval(poll, 600); return () => window.clearInterval(timer) }, [jobId, job?.status])
 function seek(at: number): void { const resume=playback.playing,position=Math.max(0,Math.min(duration,at));playback.stop(false); w.setView(v => ({ ...v, playheadMs:position }));if(resume&&position<duration)void playback.play(position,duration,w.view.loop) }
 function play(selection = false): void { if (!selection && (playback.playing || playback.loading)) { playback.stop(); return } const clip=w.project?.timeline.clips.find(c=>c.id===w.view.selectedId);const range = selection ? w.view.selection || (clip ? [clip.startMs,clipEnd(clip)] : null) : null;if(selection&&!range){w.setError('Select a fragment or range to play.');return} void playback.play(range?.[0] ?? (w.view.playheadMs >= duration ? 0 : w.view.playheadMs), range?.[1] ?? duration, w.view.loop) }
 function fit(selection = false): void { const range = selection ? w.view.selection : null; w.setView(v => ({ ...v, offsetMs: range?.[0] || 0, spanMs: Math.max(250, range ? range[1] - range[0] : duration * 1.025) })) }
 function zoom(factor: number): void { w.setView(v => { const spanMs = Math.max(250, Math.min(86400000, v.spanMs * factor)), anchor = v.playheadMs >= v.offsetMs && v.playheadMs < v.offsetMs + v.spanMs ? v.playheadMs : v.offsetMs + v.spanMs / 2, ratio = (anchor - v.offsetMs) / v.spanMs; return { ...v, spanMs, offsetMs: Math.max(0, anchor - ratio * spanMs) } }) }
 async function importFile(): Promise<void> { try { const path = await open({title:"Import audio or video reference",multiple:false,filters:[{name:"Audio or video",extensions:["wavehs","wav","mp3","m4a","aac","flac","aif","aiff","ogg","webm","mp4","mov","mkv","avi","m4v"]}]}); if (typeof path==='string') void receiveFile(path) } catch (e) { w.setError(errorMessage(e)) } }
 async function receiveFile(path: string): Promise<void> { try { if(/\.wavehs$/i.test(path)){playback.stop();await w.flush();const p=await waveApi.importBundle(path);await w.open(p.id)}else if(await waveApi.hasVideo(path)){playback.stop();await w.importVideo(path,w.view.selection?.[0]??w.view.playheadMs)}else if (duration) { setImportAt(w.view.selection?.[0]??w.view.playheadMs); setPendingImport(path) } else await w.importAudio('file', path) }catch(e){w.setError(errorMessage(e))} }

 useEffect(() => { if (!isDesktop()) return; let alive = true, cleanup: (() => void) | undefined; void getCurrentWebview().onDragDropEvent(event => { if (event.payload.type === 'drop' && alive) { const paths = event.payload.paths; if (paths.length !== 1) w.setError('Drop one audio or video file at a time.'); else if (!/\.(wav|mp3|m4a|aac|flac|aiff?|ogg|webm|mp4|mov|mkv|avi|m4v|wavehs)$/i.test(paths[0]!)) w.setError('Choose an audio file or a video reference.'); else void receiveFile(paths[0]!) } }).then(fn => { if (alive) cleanup = fn; else fn() }).catch(e => w.setError(errorMessage(e))); return () => { alive = false; cleanup?.() } }, [duration])
 function selectAll(): void { w.setView(v => ({ ...v, selection: duration ? [0, duration] : null, selectedId: null, selectedIds: [] })) }
 function remove(silenceInstead = false): void { if (!w.project) return; const sfx = w.project.timeline.sfx.find(c => c.id === w.view.selectedId), voice = w.project.timeline.voices.find(v => v.id === w.view.selectedId); if (sfx && !silenceInstead) w.edit({ ...w.project.timeline, sfx: w.project.timeline.sfx.filter(c => c.id !== sfx.id) }); else if (voice && !silenceInstead) w.edit({ ...w.project.timeline, voices: w.project.timeline.voices.filter(v => v.id !== voice.id) }); else if (w.view.selection) { w.edit(removeRange(w.project.timeline, ...w.view.selection, silenceInstead)); w.setView(v => ({ ...v, selection: null, selectedId: null, selectedIds: [], playheadMs: Math.min(v.playheadMs, w.view.selection![0]) })) } else { const c = w.project.timeline.clips.find(c => c.id === w.view.selectedId); if (c) w.edit(removeRange(w.project.timeline, c.startMs, clipEnd(c), silenceInstead)) } }
 function applySpeed(n: number): void { if (w.project && w.view.selection && n >= .85 && n <= 1.2) { w.edit(changeSpeed(w.project.timeline, ...w.view.selection, n)); w.setView(v => ({ ...v, selection: null })); setSpeedMenu(false) } }
 function addSilence(n: number): void { if (w.project && n > 0 && Number.isFinite(n)) { w.edit(insertSilence(w.project.timeline, w.view.playheadMs, n)); setSilenceMenu(false) } }
 useEffect(() => { const key = (e: KeyboardEvent) => { const target = e.target as HTMLElement; if (e.key === 'Escape' && (projects || pendingImport)) { setProjects(false); setPendingImport(null); return } if (help || joinChoices || exportPanel || recordPanel || productionKind || projects || pendingImport || target.closest('input,textarea,select,[contenteditable="true"]') || e.altKey) return; const cmd = e.metaKey || e.ctrlKey; if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();const right=e.key==='ArrowRight',clips=[...(w.project?.timeline.clips||[])].sort((a,b)=>a.startMs-b.startMs),selected=clips.find(c=>c.id===w.view.selectedId);if(e.shiftKey)seek(w.view.playheadMs+(right?5000:-5000));else if(cmd){const clip=selected||clips.find(c=>w.view.playheadMs>=c.startMs&&w.view.playheadMs<=clipEnd(c));if(clip)seek(right?clipEnd(clip):clip.startMs);}else {const index=selected?clips.indexOf(selected):clips.findIndex(c=>w.view.playheadMs>=c.startMs&&w.view.playheadMs<clipEnd(c)),clip=clips[Math.max(0,Math.min(clips.length-1,index+(right?1:-1)))];if(clip){w.setView(v=>({...v,selectedId:clip.id,selectedIds:[clip.id],selection:null}));seek(clip.startMs)}}return} if (cmd && e.key.toLowerCase() === 'z') { e.preventDefault(); e.shiftKey ? w.redo() : w.undo() } else if (cmd && e.key.toLowerCase() === 'a') { e.preventDefault(); selectAll() } else if (!cmd) { if (e.code === 'Space') { e.preventDefault(); play(e.shiftKey) } else if (e.key === 's' || e.key === 'S') { if (w.project) w.edit(splitAt(w.project.timeline, w.view.playheadMs)) } else if (e.key === 'Delete' || e.key === 'Backspace') { e.preventDefault(); remove() } else if (e.key === 'Escape') { w.setView(v => ({ ...v, selection: null, selectedId: null, selectedIds: [] })); setVoiceMenu(false); setSpeedMenu(false); setSilenceMenu(false); setDrawer(false) } else if (e.key === '+' || e.key === '=') zoom(1 / 1.5); else if (e.key === '-') zoom(1.5); else if (e.key === '0') fit() } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key) })
 async function showProjects():Promise<void>{playback.stop();try{await w.flush();setProjects(true)}catch(e){w.setError(errorMessage(e))}}

 return <div className="wave-studio-page" onDragOver={e=>{if(!isDesktop()&&e.dataTransfer.types.includes("Files"))e.preventDefault()}} onDrop={e=>{if(isDesktop()||!e.dataTransfer.files.length)return;e.preventDefault();if(e.dataTransfer.files.length!==1){w.setError("Drop one file at a time.");return}const file=e.dataTransfer.files[0]!;void uploadFile(file,file.name).then(receiveFile).catch(e=>w.setError(errorMessage(e)))}}><WaveStudioToolbar playing={playback.playing} loading={playback.loading} play={play} seek={seek} fit={fit} zoom={zoom} onImport={() => void importFile()} onExport={()=>{playback.stop();setExportPanel(true)}} onProjects={() => void showProjects()} onRecord={() => void openProduction('record')} onSpeech={() => void openProduction('speech')} onJoin={() => { if(!joining) void join() }} onVoices={() => void openProduction('voices')} />
 {activeJobs.map(job=><div key={job.id} className="wave-message" role="status">{job.label} · {job.progress}%<button onClick={()=>void systemApi.controlJob(job.id,"cancel").catch(e=>w.setError(errorMessage(e)))}>Cancel generation</button></div>)}
 {w.error && <div className="wave-message inline-error" role="alert">{w.error}<button onClick={() => w.setError('')}>Dismiss</button></div>}
 {job && <div className="wave-message" role="status">Export {job.status} · {job.progress}% {job.message}{['queued', 'running', 'paused'].includes(job.status) && <button onClick={() => void systemApi.controlJob(job.id, 'cancel')}>Cancel</button>}</div>}
 {duration ? <><div className="wave-edit-bar"><button onClick={selectAll}>Select all</button><button disabled={!w.view.selection && !w.view.selectedId} onClick={() => remove()}>Delete & close gap</button><button disabled={!w.view.selection} onClick={() => remove(true)}>Replace with silence</button><button onClick={() => { if (w.project) w.edit(splitAt(w.project.timeline, w.view.playheadMs)) }}>Split (S)</button><button disabled={joining || !w.project || joinCandidateIds(w.project.timeline,w.view.selection,w.view.playheadMs,w.view.selectedId,w.view.selectedIds).length<2} onClick={()=>void join()}>{joining?'Joining…':'Join'}</button><div className="wave-menu-wrap"><button onClick={() => setSilenceMenu(!silenceMenu)}>Insert silence ▾</button>{silenceMenu && <div className="wave-popover"><p>At {formatWaveTime(w.view.playheadMs)}</p><div className="wave-presets">{[250, 500, 1000, 2000].map(n => <button key={n} onClick={() => addSilence(n)}>{n / 1000}s</button>)}</div><label>Duration (ms)<input type="number" min={1} max={86400000} value={silence} onChange={e => setSilence(Number(e.target.value))} /></label><button disabled={silence <= 0} onClick={() => addSilence(silence)}>Insert</button></div>}</div>
 <div className="wave-menu-wrap"><button disabled={!w.view.selection} onClick={() => { setVoiceMenu(!voiceMenu); void productionApi.voices().then(setVoices).catch(e => w.setError(errorMessage(e))) }}>Voice ▾</button>{voiceMenu && <div className="wave-popover"><p>Assign a voice to this passage</p>{[...voices].sort((a, b) => { const recent = readRecentVoices(); return (recent.includes(a.id) ? recent.indexOf(a.id) : 99) - (recent.includes(b.id) ? recent.indexOf(b.id) : 99) }).slice(0, 12).map(v => <button className="wave-voice-choice" key={v.id} onClick={() => { if (w.project && w.view.selection) w.edit(assignVoice(w.project.timeline, ...w.view.selection, v)); localStorage.setItem('homer.wave.recentVoices', JSON.stringify([v.id,...readRecentVoices().filter(id=>id!==v.id)].slice(0,12))); setVoiceMenu(false) }}><i style={{ background: voiceColor(v) }} />{v.name}</button>)}<button onClick={() => onNavigate('voices')}>Manage / create voices →</button></div>}</div>
 <div className="wave-menu-wrap"><button disabled={!w.view.selection} onClick={() => setSpeedMenu(!speedMenu)}>Speed ▾</button>{speedMenu && <div className="wave-popover"><p>Pitch preserved</p><NeutralSlider label={`Speed · ${Math.round((customSpeed-1)*100)}%`} min={.85} max={1.2} neutral={1} step={.01} value={customSpeed} onChange={setCustomSpeed} />{w.view.selection && <p>{formatWaveTime(w.view.selection[1] - w.view.selection[0])} → {formatWaveTime(changedSelectionDuration)}</p>}<button onClick={() => applySpeed(customSpeed)}>Apply speed</button></div>}</div>
 <button onClick={()=>setHelp(true)}>Keyboard shortcuts</button><button className="wave-add-sfx" onClick={() => setDrawer(!drawer)}>♪ Add SFX</button><button disabled={!w.view.selection} onClick={() => play(true)}>Play selection</button>{w.project?.voiceOriginal&&<button onClick={()=>{playback.stop();w.restoreOriginal()}}>Restore pre-conversion timeline</button>}</div>
 <div className="wave-editor-grid"><div className="wave-editor-body"><div className="wave-timeline-column">{!!w.project!.videos?.length&&<WaveVideoReference key={w.project!.id} videos={w.project!.videos} view={w.view} playing={playback.playing} setVideos={v=>{playback.stop();w.setVideos(v)}} setView={w.setView} onError={w.setError}/>}
<WaveStudioTimeline videos={w.project!.videos||[]} setVideos={v=>{playback.stop();w.setVideos(v)}} durationMs={duration} timeline={w.project!.timeline} view={w.view} setView={w.setView} edit={w.edit} onSeek={seek} onSfxDrop={(id, at, lane) => { void waveApi.sfx().then(assets => { const a = assets.find(a => a.id === id); if (a) w.addSource(a, at, lane) }).catch(e => w.setError(errorMessage(e))) }} onError={w.setError} /></div>{drawer && <WaveStudioLibraryDrawer onClose={() => setDrawer(false)} onManage={() => onNavigate('sfx')} />}</div><WaveStudioInspector onGenerateVoice={id=>{playback.stop();setProductionRegion(id);setProductionKind('voices')}} onListenVoice={id=>{const r=w.project?.timeline.voices.find(v=>v.id===id);if(r){playback.stop();void playback.play(r.startMs,r.endMs,false)}}} voices={voices} onManageVoices={() => onNavigate('voices')} /></div></> : <div className="wave-empty"><div className="wave-empty-mark">▥</div><h1>Your story starts here</h1><p>Record here or drop audio into Wave Studio.<br />Shape your narration, mark voices and add sound effects.</p><div><button className="primary" disabled={w.busy || !hasBackend()} onClick={() => void openProduction('record')}>Record here</button><button disabled={w.busy || !hasBackend()} onClick={() => void openProduction('speech')}>Generate speech</button><button disabled={w.busy || !hasBackend()} onClick={() => void importFile()}>Import audio</button><button disabled={w.busy || !hasBackend()} onClick={() => void showProjects()}>Open recent project</button></div><small>WAV · MP3 · M4A · AAC · FLAC</small><button className="wave-empty-link" onClick={() => onNavigate('voice-memos')}>Record a voice memo →</button></div>}
 {help&&<div className="wave-dialog-backdrop"><section className="wave-dialog" role="dialog" aria-modal="true" aria-label="Keyboard shortcuts"><h2>Keyboard shortcuts</h2><p>Space — Play / stop</p><p>Shift + Space — Play selected fragment or range</p><p>← / → — Previous / next fragment</p><p>Control or Command + ← / → — Selected fragment start / end</p><p>Shift + ← / → — Skip five seconds</p><p>S — Split · + / − — Zoom · 0 — Fit</p><p>Shift-click — Add to selection · Command-click — Toggle selection</p><p>Double-click — Select whole fragment</p><button onClick={()=>setHelp(false)}>Close</button></section></div>}
 {joinChoices&&<div className="wave-dialog-backdrop"><section className="wave-dialog" role="dialog" aria-modal="true" aria-label="Join voice"><h2>Choose a voice for the joined fragment</h2><p>These fragments have different voice tags. Assign one tag to the joined passage. Generate the voice afterwards to change its sound.</p>{voices.filter(v=>joinChoices.includes(v.id)).map(v=><button key={v.id} onClick={()=>void join(v.id)}>{v.name}</button>)}<button onClick={()=>void join(null)}>Clear voice tags</button><button onClick={()=>setJoinChoices(null)}>Cancel</button></section></div>}
 {pendingImport && <div className="wave-dialog-backdrop"><section className="wave-dialog" role="dialog" aria-modal="true" aria-label="Import audio"><h2>Add audio to this project</h2><p>{pendingImport.split('/').pop()}</p><label>Insertion position (seconds)<input type="number" min={0} step={.001} value={importAt/1000} onChange={e=>setImportAt(Math.max(0,Number(e.target.value)*1000))}/></label><button onClick={()=>setImportAt(w.view.selection?.[0]??w.view.playheadMs)}>Use selection / playhead</button><button onClick={()=>setImportAt(duration)}>Use end</button>{(['insert', 'append', 'sfx', 'replace'] as const).map(mode => <button key={mode} disabled={w.busy} onClick={() => { const path = pendingImport; setPendingImport(null); void w.importAudio('file', path, mode, importAt) }}>{mode === 'insert' ? 'Insert into narration at this position' : mode === 'append' ? 'Append to narration' : mode === 'sfx' ? 'Add as sound effect' : 'Replace narration (can undo)'}</button>)}<button onClick={() => setPendingImport(null)}>Cancel</button></section></div>}
 {projects&&<div className="wave-dialog-backdrop"><WaveProjectsPanel onClose={()=>setProjects(false)}/></div>}
 {exportPanel&&<div className="wave-dialog-backdrop"><WaveExportPanel onClose={()=>setExportPanel(false)} onJob={id=>{setJob(null);setJobId(id)}}/></div>}

 {recordPanel&&w.project&&<div className="wave-dialog-backdrop"><WaveRecordingPanel key={w.project.id} onRecorded={async id=>{const projectId=w.project!.id,source=await waveApi.import('memo',null,id);if(latest.current.project?.id!==projectId)throw new Error('Project changed. Import this recording from Voice Memos.');latest.current.addSource(source,undefined,'main')}} onClose={()=>setRecordPanel(false)}/></div>}
 {productionKind&&w.project&&<div className="wave-dialog-backdrop"><WaveProductionPanel key={`${w.project.id}-${productionKind}`} kind={productionKind} regionId={productionRegion} voices={voices} onClose={()=>setProductionKind(null)}/></div>}
 </div>
}
