import {WaveAudioImportPanel} from './components/WaveAudioImportPanel'
import {arrangeVideos,videosOverlap} from '../../shared/waveStudio'
import {StudioIcon} from './components/StudioIcon'
import {StudioModal} from './components/StudioModal'
import {useToast} from './components/StudioToast'
import { isDesktop, uploadFile } from './platform'
import { NeutralSlider } from './components/NeutralSlider'
import { useEffect, useRef, useState } from 'react'
import { getCurrentWebview } from '@tauri-apps/api/webview'
import { open } from './platform'
import type { Voice, JobRecord } from '../../shared/contracts'
import type { RouteId } from '../../shared/navigation'
import { sourceClip, clipEnd, voiceColor, voiceAudioKey, formatWaveTime, timelineDuration, projectDuration } from '../../shared/waveStudio'
import { joinCandidateIds, replaceRange, restoreVoiceOriginal, assignVoice, changeSpeed, insertSilence, removeRange, splitAt, splitSoundtrack } from '../../shared/waveStudioEdits'
import { useWaveStudio } from './WaveStudioProvider'
import { useWaveStudioPlayback } from './useWaveStudioPlayback'
import { errorMessage, hasBackend, productionApi, systemApi } from './native'
import { waveApi } from './waveStudioNative'
import { WaveStudioToolbar } from './components/WaveStudioToolbar'
import { WaveStudioTimeline } from './components/WaveStudioTimeline'
import { WaveStudioInspector } from './components/WaveStudioInspector'
import { WaveStudioLibraryDrawer } from './components/WaveStudioLibraryDrawer'
import { WaveRecordingPanel } from './components/WaveRecordingPanel'
import { WaveExportPanel } from './components/WaveExportPanel'
import { WaveProjectsPanel } from './components/WaveProjectsPanel'
import { WaveVideoReference } from './components/WaveVideoReference'
import { WaveProductionPanel } from './components/WaveProductionPanel'
function readRecentVoices(): string[] { try { const value: unknown=JSON.parse(localStorage.getItem('homer.wave.recentVoices') || '[]'); return Array.isArray(value) ? value.filter((id): id is string=>typeof id==='string') : [] } catch { return [] } }
export function WaveStudioPage({ onNavigate }: { onNavigate: (route: RouteId) => void }): JSX.Element {
 const w = useWaveStudio(), [drawer, setDrawer] = useState(false), [voices, setVoices] = useState<Voice[]>([]), [voiceMenu, setVoiceMenu] = useState(false), [speedMenu, setSpeedMenu] = useState(false), [silenceMenu, setSilenceMenu] = useState(false), [silence, setSilence] = useState(500), [customSpeed, setCustomSpeed] = useState(1), [pendingImport, setPendingImport] = useState<string | null>(null), [projects, setProjects] = useState(false), [exportPanel,setExportPanel]=useState(false), [job, setJob] = useState<JobRecord | null>(null), [jobId, setJobId] = useState('')
 const [recordPanel,setRecordPanel]=useState(false),[productionKind,setProductionKind]=useState<'speech'|'voices'|null>(null),[joining,setJoining]=useState(false),[productionRegion,setProductionRegion]=useState<string|undefined>()
 const [help,setHelp]=useState(false),[joinChoices,setJoinChoices]=useState<string[]|null>(null)
 const [activeJobs,setActiveJobs]=useState<JobRecord[]>([])
 useEffect(()=>{if(!hasBackend())return;let alive=true;const poll=()=>{void systemApi.jobs().then(jobs=>{if(alive)setActiveJobs(jobs.filter(j=>j.kind==='wave_processing'&&['queued','running'].includes(j.status)))}).catch(()=>{})};poll();const timer=window.setInterval(poll,700);return()=>{alive=false;window.clearInterval(timer)}},[])
 const latest=useRef(w);latest.current=w
 async function openProduction(kind:'record'|'speech'|'voices'):Promise<void>{playback.stop();if(!w.project)await w.create();if(kind==='record')setRecordPanel(true);else {setProductionRegion(undefined);setProductionKind(kind)}}
 async function join(choice?:string|null):Promise<void>{if(!w.project)return;const p=w.project, ids=joinCandidateIds(p.timeline,w.view.selection,w.view.playheadMs,w.view.selectedId,w.view.selectedIds);if(ids.length<2){w.setError('Select at least two adjacent narration clips, or select a clip and its next neighbour.');return}const selected=p.timeline.clips.filter(c=>ids.includes(c.id)),a=Math.min(...selected.map(c=>c.startMs)),b=Math.max(...selected.map(clipEnd)),regions=p.timeline.voices.filter(v=>v.startMs<b&&v.endMs>a),tags=[...new Set(regions.map(v=>v.voiceId))];if(choice===undefined&&(tags.length>1||(tags.length===1&&regions.reduce((n,v)=>n+Math.min(b,v.endMs)-Math.max(a,v.startMs),0)<b-a))){setJoinChoices(tags);return}setJoinChoices(null);setJoining(true);playback.stop();try{const source=await waveApi.join(p,ids);if(latest.current.project?.id!==p.id||JSON.stringify(latest.current.project.timeline)!==JSON.stringify(p.timeline))throw new Error('Project changed during Join. Retry with the current selection.');const clips=p.timeline.clips.filter(c=>ids.includes(c.id)),start=Math.min(...clips.map(c=>c.startMs)),end=Math.max(...clips.map(clipEnd)),clip=sourceClip(source,start);clip.sourceEndMs=end-start;const joined=replaceRange(p.timeline,start,end,clip);const chosen=choice===undefined?tags[0]:choice;const voice=voices.find(v=>v.id===chosen);if(voice)joined.voices=assignVoice(joined,start,end,voice).voices;else joined.voices=joined.voices.flatMap(v=>v.endMs<=start||v.startMs>=end?[v]:[...(v.startMs<start?[{...v,endMs:start,production:undefined}]:[]),...(v.endMs>end?[{...v,startMs:end,production:undefined}]:[])]);w.edit(joined,[...p.sources,source]);w.setView(v=>({...v,selection:[start,end],selectedId:clip.id,selectedIds:[clip.id]}))}catch(e){w.setError(errorMessage(e))}finally{setJoining(false)}}
 const duration = w.project ? projectDuration(w.project) : 0
 const changedSelectionDuration = w.project && w.view.selection ? w.view.selection[1]-w.view.selection[0]+timelineDuration(changeSpeed(w.project.timeline,...w.view.selection,customSpeed))-timelineDuration(w.project.timeline) : 0
 useEffect(() => { if (!w.project || !voices.length) return; let changed=false; const regions=w.project.timeline.voices.map(r => { const v=voices.find(v=>v.id===r.voiceId); if (!v || (r.name===v.name && r.color===(voiceColor(v)))) return r; changed=true; return {...r,name:v.name,color:voiceColor(v)} }); if(changed) w.edit({...w.project.timeline,voices:regions}) }, [voices])
 const playback = useWaveStudioPlayback(w.project, ms => w.setView(v => ({ ...v, playheadMs: ms })), w.setError)
 useEffect(() => { if (hasBackend()) void productionApi.voices().then(setVoices).catch(e => w.setError(errorMessage(e))) }, [])
 useEffect(() => { if (!jobId || ['completed', 'failed', 'cancelled'].includes(job?.status || '')) return; const poll = () => { void systemApi.jobs().then(jobs => { const found = jobs.find(j => j.id === jobId); if (found) { setJob(found); if (found.status === 'failed') w.setError(found.message || 'Export failed') } }).catch(e => w.setError(errorMessage(e))) }; poll(); const timer = window.setInterval(poll, 600); return () => window.clearInterval(timer) }, [jobId, job?.status])
 function seek(at: number): void { const resume=playback.playing,position=Math.max(0,Math.min(duration,at));playback.stop(false); w.setView(v => ({ ...v, playheadMs:position,offsetMs:position<v.offsetMs+v.spanMs*.1?Math.max(0,position-v.spanMs*.1):position>v.offsetMs+v.spanMs*.9?Math.max(0,position-v.spanMs*.9):v.offsetMs }));if(resume&&position<duration)void playback.play(position,duration,w.view.loop) }
 function play(selection = false): void { if (!selection && (playback.playing || playback.loading)) { playback.stop(); return } const clip=w.project?.timeline.clips.find(c=>c.id===w.view.selectedId);const range = selection ? w.view.selection || (clip ? [clip.startMs,clipEnd(clip)] : null) : null;if(selection&&!range){w.setError('Select a fragment or range to play.');return} void playback.play(range?.[0] ?? (w.view.playheadMs >= duration ? 0 : w.view.playheadMs), range?.[1] ?? duration, w.view.loop) }
 function fit(selection = false): void { const range = selection ? w.view.selection : null; w.setView(v => ({ ...v, offsetMs: range?.[0] || 0, spanMs: Math.max(250, range ? range[1] - range[0] : duration * 1.025) })) }
 function zoom(factor: number): void { w.setView(v => { const spanMs = Math.max(250, Math.min(86400000, v.spanMs * factor)), anchor = v.playheadMs >= v.offsetMs && v.playheadMs < v.offsetMs + v.spanMs ? v.playheadMs : v.offsetMs + v.spanMs / 2, ratio = (anchor - v.offsetMs) / v.spanMs; return { ...v, spanMs, offsetMs: Math.max(0, anchor - ratio * spanMs) } }) }
 function dropTarget(x:number,y:number):{lane:'main'|'sfx';at:number}|undefined{const element=document.elementFromPoint(x,y)?.closest('.wave-main-lane,.wave-sfx-lane');if(!element)return;const rect=element.getBoundingClientRect(),v=latest.current.view;return {lane:element.classList.contains('wave-main-lane')?'main':'sfx',at:Math.max(0,v.offsetMs+(x-rect.left)/rect.width*v.spanMs)}}
 function highlight(x?:number,y?:number):void{document.querySelectorAll('.wave-file-drop-target').forEach(e=>e.classList.remove('wave-file-drop-target'));if(x!==undefined&&y!==undefined)document.elementFromPoint(x,y)?.closest('.wave-main-lane,.wave-sfx-lane,.wave-video-lane')?.classList.add('wave-file-drop-target')}
 async function importFile():Promise<void>{try{const paths=await open({title:'Import audio or video',multiple:true,filters:[{name:'Audio or video',extensions:['wavehs','wav','mp3','m4a','aac','flac','aif','aiff','ogg','webm','mp4','mov','mkv','avi','m4v']}]});if(paths)await receiveFiles(typeof paths==='string'?[paths]:paths)}catch(e){latest.current.setError(errorMessage(e))}}
 async function receiveFiles(paths:string[],target?:{lane:'main'|'sfx';at:number}):Promise<void>{try{const studio=latest.current;playback.stop();if(paths.some(p=>/\.wavehs$/i.test(p))){if(paths.length!==1)throw new Error('Open one project at a time.');await studio.openBundle(paths[0]!);return}const videoFlags=await Promise.all(paths.map(p=>/\.(mp4|mov|mkv|avi|m4v)$/i.test(p)?Promise.resolve(true):waveApi.hasVideo(p)));if(videoFlags.every(Boolean)){await studio.importVideos(paths,target?.at??studio.view.playheadMs);return}if(paths.length!==1)throw new Error('Select multiple videos together, or add one audio file at a time.');if(target)await studio.importAudio('file',paths[0]!,target.lane==='main'?'insert':'sfx',target.at);else if(studio.project&&projectDuration(studio.project))setPendingImport(paths[0]!);else await studio.importAudio('file',paths[0]!)}catch(e){latest.current.setError(errorMessage(e))}}
 useEffect(()=>{if(!isDesktop())return;let alive=true,cleanup:(()=>void)|undefined;void getCurrentWebview().onDragDropEvent(event=>{if(!alive)return;const payload=event.payload;if(payload.type==='leave'){highlight();return}if('position' in payload){const x=payload.position.x/window.devicePixelRatio,y=payload.position.y/window.devicePixelRatio;highlight(x,y);if(payload.type==='drop'){highlight();if(!payload.paths.some(p=>/\.wavehs$/i.test(p)))void receiveFiles(payload.paths,dropTarget(x,y))}}}).then(fn=>{if(alive)cleanup=fn;else fn()}).catch(e=>latest.current.setError(errorMessage(e)));return()=>{alive=false;cleanup?.();highlight()}},[])
 function selectAll(): void { w.setView(v => ({ ...v, selection: duration ? [0, duration] : null, selectedId: null, selectedIds: [] })) }
 function split():void { if(!w.project)return;playback.stop();const id=w.view.selectedId;if(w.project.videos?.some(v=>v.id===id))return;w.edit(w.project.timeline.sfx.some(c=>c.id===id)?splitSoundtrack(w.project.timeline,id!,w.view.playheadMs):splitAt(w.project.timeline,w.view.playheadMs)) }
 function remove(silenceInstead = false): void { if (!w.project) return;playback.stop();const video=w.project.videos?.find(v=>v.id===w.view.selectedId);if(video&&!silenceInstead){w.setVideos(w.project.videos!.filter(v=>v.id!==video.id));w.setView(v=>({...v,selectedId:null,selectedIds:[],selection:null}));return} const sfx = w.project.timeline.sfx.find(c => c.id === w.view.selectedId), voice = w.project.timeline.voices.find(v => v.id === w.view.selectedId); if (sfx && !silenceInstead) {w.edit({ ...w.project.timeline, sfx: w.project.timeline.sfx.filter(c => c.id !== sfx.id) });w.setView(v=>({...v,selectedId:null,selectedIds:[],selection:null}))} else if (voice && !silenceInstead) w.edit({ ...w.project.timeline, voices: w.project.timeline.voices.filter(v => v.id !== voice.id) }); else if (w.view.selection) { w.edit(removeRange(w.project.timeline, ...w.view.selection, silenceInstead)); w.setView(v => ({ ...v, selection: null, selectedId: null, selectedIds: [], playheadMs: Math.min(v.playheadMs, w.view.selection![0]) })) } else { const c = w.project.timeline.clips.find(c => c.id === w.view.selectedId); if (c) w.edit(removeRange(w.project.timeline, c.startMs, clipEnd(c), silenceInstead)) } }
 function applySpeed(n: number): void { if (w.project && w.view.selection && n >= .85 && n <= 1.2) { w.edit(changeSpeed(w.project.timeline, ...w.view.selection, n)); w.setView(v => ({ ...v, selection: null })); setSpeedMenu(false) } }
 function addSilence(n: number): void { if (w.project && n > 0 && Number.isFinite(n)) { w.edit(insertSilence(w.project.timeline, w.view.playheadMs, n)); setSilenceMenu(false) } }
 useEffect(() => { const key = (e: KeyboardEvent) => { const target = e.target as HTMLElement; if(e.defaultPrevented||document.querySelector('[role=dialog][aria-modal=true],dialog[open]'))return; if (help || joinChoices || exportPanel || recordPanel || productionKind || projects || pendingImport || target.closest('input,textarea,select,[contenteditable="true"]') || e.altKey) return; const cmd = e.metaKey || e.ctrlKey; if(e.key==='ArrowLeft'||e.key==='ArrowRight'||e.key==='<'||e.key==='>'){e.preventDefault();const right=e.key==='ArrowRight'||e.key==='>',clips=[...(w.project?.timeline.clips||[])].sort((a,b)=>a.startMs-b.startMs),selected=clips.find(c=>c.id===w.view.selectedId);if(e.shiftKey&&e.key!=='<'&&e.key!=='>')seek(w.view.playheadMs+(right?5000:-5000));else if(cmd){const clip=selected||clips.find(c=>w.view.playheadMs>=c.startMs&&w.view.playheadMs<=clipEnd(c));if(clip)seek(right?clipEnd(clip):clip.startMs);}else {const index=selected?clips.indexOf(selected):clips.findIndex(c=>w.view.playheadMs>=c.startMs&&w.view.playheadMs<clipEnd(c)),clip=clips[Math.max(0,Math.min(clips.length-1,index+(right?1:-1)))];if(clip){w.setView(v=>({...v,selectedId:clip.id,selectedIds:[clip.id],selection:null}));seek(right&&index===clips.length-1?clipEnd(clip):clip.startMs)}}return} if (cmd && e.key.toLowerCase() === 'z') { e.preventDefault(); e.shiftKey ? w.redo() : w.undo() } else if (cmd && e.key.toLowerCase() === 'a') { e.preventDefault(); selectAll() } else if (!cmd) { if (e.code === 'Space') { e.preventDefault(); play(e.shiftKey) } else if (e.key === 's' || e.key === 'S') { split() } else if (e.key === 'Delete' || e.key === 'Backspace') { e.preventDefault(); remove() } else if (e.key === 'Escape') { w.setView(v => ({ ...v, selection: null, selectedId: null, selectedIds: [] })); setVoiceMenu(false); setSpeedMenu(false); setSilenceMenu(false); setDrawer(false) } else if (e.key === '+' || e.key === '=') zoom(1 / 1.5); else if (e.key === '-') zoom(1.5); else if (e.key === '0') fit() } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key) })
 async function showProjects():Promise<void>{playback.stop();try{await w.flush();setProjects(true)}catch(e){w.setError(errorMessage(e))}}

 useToast(w.error,'error')
 return <div className="wave-studio-page" onDragOver={e=>{if(!isDesktop()&&e.dataTransfer.types.includes('Files')){e.preventDefault();highlight(e.clientX,e.clientY)}}} onDragLeave={()=>highlight()} onDrop={e=>{if(isDesktop()||!e.dataTransfer.files.length)return;e.preventDefault();highlight();const target=dropTarget(e.clientX,e.clientY),files=Array.from(e.dataTransfer.files);void (async()=>{const paths:string[]=[];for(const file of files)paths.push(await uploadFile(file,file.name));await receiveFiles(paths,target)})().catch(e=>w.setError(errorMessage(e)))}}><WaveStudioToolbar playing={playback.playing} loading={playback.loading} play={play} seek={seek} fit={fit} zoom={zoom} onImport={() => void importFile()} onExport={()=>{playback.stop();setExportPanel(true)}} onProjects={() => void showProjects()} onRecord={() => void openProduction('record')} onSpeech={() => void openProduction('speech')} onJoin={() => { if(!joining) void join() }} onVoices={() => void openProduction('voices')} />
 {w.operation&&<div className="wave-message" role="status">{w.operation.label} / {w.operation.progress}%<progress max={100} value={w.operation.progress}/><button onClick={w.cancelOperation}>Cancel import</button></div>}
 {videosOverlap(w.project?.videos||[])&&<div className="wave-message">These video fragments overlap. Arrange them before saving or exporting.<button onClick={()=>{try{w.setVideos(arrangeVideos(w.project?.videos||[]))}catch(e){w.setError(errorMessage(e))}}}>Arrange videos sequentially</button></div>}
 {activeJobs.map(job=><div key={job.id} className="wave-message" role="status">{job.label}  /  {job.progress}%<button onClick={()=>void systemApi.controlJob(job.id,"cancel").catch(e=>w.setError(errorMessage(e)))}>Cancel generation</button></div>)}

 {jobId && !job && <div className="wave-message" role="status">Export queued…<progress aria-label="Export progress"/></div>}
 {job && <div className="wave-message" role="status">Export {job.status}  /  {job.progress}% {job.message}<progress aria-label="Export progress" max={100} value={job.progress}/>{['queued', 'running', 'paused'].includes(job.status) && <button onClick={() => void systemApi.controlJob(job.id, 'cancel')}>Cancel</button>}</div>}
 {duration ? <><div className="wave-edit-bar"><button onClick={selectAll}>Select all</button><button disabled={!w.view.selection && !w.view.selectedId} onClick={() => remove()}>{w.project?.videos?.some(v=>v.id===w.view.selectedId)?'Delete video':w.project?.timeline.sfx.some(c=>c.id===w.view.selectedId)?'Delete soundtrack':'Delete & close gap'}</button><button disabled={!w.view.selection} onClick={() => remove(true)}>Replace with silence</button><button onClick={() => { split() }}>Split (S)</button><button disabled={joining || !w.project || joinCandidateIds(w.project.timeline,w.view.selection,w.view.playheadMs,w.view.selectedId,w.view.selectedIds).length<2} onClick={()=>void join()}>{joining?'Joining...':'Join'}</button><div className="wave-menu-wrap"><button onClick={() => setSilenceMenu(!silenceMenu)}>Insert silence v</button>{silenceMenu && <div className="wave-popover"><p>At {formatWaveTime(w.view.playheadMs)}</p><div className="wave-presets">{[250, 500, 1000, 2000].map(n => <button key={n} onClick={() => addSilence(n)}>{n / 1000}s</button>)}</div><label>Duration (ms)<input type="number" min={1} max={86400000} value={silence} onChange={e => setSilence(Number(e.target.value))} /></label><button disabled={silence <= 0} onClick={() => addSilence(silence)}>Insert</button></div>}</div>
 <div className="wave-menu-wrap"><button disabled={!w.view.selection} onClick={() => { setVoiceMenu(!voiceMenu); void productionApi.voices().then(setVoices).catch(e => w.setError(errorMessage(e))) }}>Voice v</button>{voiceMenu && <div className="wave-popover"><p>Assign a voice to this passage</p>{[...voices].sort((a, b) => { const recent = readRecentVoices(); return (recent.includes(a.id) ? recent.indexOf(a.id) : 99) - (recent.includes(b.id) ? recent.indexOf(b.id) : 99) }).slice(0, 12).map(v => <button className="wave-voice-choice" key={v.id} onClick={() => { if (w.project && w.view.selection) w.edit(assignVoice(w.project.timeline, ...w.view.selection, v)); localStorage.setItem('homer.wave.recentVoices', JSON.stringify([v.id,...readRecentVoices().filter(id=>id!==v.id)].slice(0,12))); setVoiceMenu(false) }}><i style={{ background: voiceColor(v) }} />{v.name}</button>)}<button onClick={() => onNavigate('voices')}>Manage / create voices</button></div>}</div>
 <div className="wave-menu-wrap"><button disabled={!w.view.selection} onClick={() => setSpeedMenu(!speedMenu)}>Speed v</button>{speedMenu && <div className="wave-popover"><p>Pitch preserved</p><NeutralSlider label={`Speed  /  ${Math.round((customSpeed-1)*100)}%`} min={.85} max={1.2} neutral={1} step={.01} value={customSpeed} onChange={setCustomSpeed} />{w.view.selection && <p>{formatWaveTime(w.view.selection[1] - w.view.selection[0])} to {formatWaveTime(changedSelectionDuration)}</p>}<button onClick={() => applySpeed(customSpeed)}>Apply speed</button></div>}</div>
 {w.project?.timeline.voices.filter(v=>v.audio&&(w.view.selection?v.startMs<w.view.selection[1]&&v.endMs>w.view.selection[0]:v.startMs<=w.view.playheadMs&&v.endMs>w.view.playheadMs)).map(v=><button key={v.id} onClick={()=>{playback.stop();w.edit(restoreVoiceOriginal(w.project!.timeline,v.id))}}>Restore original audio ({v.name})</button>)}<button onClick={()=>setHelp(true)}>Keyboard shortcuts</button><button className="wave-add-sfx" onClick={() => setDrawer(!drawer)}>SFX Add SFX</button><button disabled={!w.view.selection} onClick={() => play(true)}>Play selection</button>{w.project?.voiceOriginal&&!w.project.timeline.voices.some(v=>v.audio)&&<button onClick={()=>{playback.stop();w.restoreOriginal()}}>Restore pre-conversion timeline</button>}</div>
 <div className="wave-editor-grid"><div className="wave-editor-body"><div className="wave-timeline-column">{!!w.project!.videos?.length&&<WaveVideoReference key={w.project!.id} videos={w.project!.videos} view={w.view} playing={playback.playing} setVideos={v=>{playback.stop();w.setVideos(v)}} setView={w.setView} onError={w.setError}/>}
<WaveStudioTimeline sources={w.project!.sources} videos={w.project!.videos||[]} setVideos={v=>{playback.stop();w.setVideos(v)}} durationMs={duration} timeline={w.project!.timeline} view={w.view} setView={w.setView} edit={w.edit} onSeek={seek} onSfxDrop={(id, at, lane) => { void waveApi.sfx().then(assets => { const a = assets.find(a => a.id === id); if (a) w.addSource(a, at, lane) }).catch(e => w.setError(errorMessage(e))) }} onError={w.setError} /></div>{drawer && <WaveStudioLibraryDrawer onClose={() => setDrawer(false)} onManage={() => onNavigate('sfx')} />}</div><WaveStudioInspector onGenerateVoice={id=>{playback.stop();setProductionRegion(id);setProductionKind('voices')}} onListenVoice={id=>{const r=w.project?.timeline.voices.find(v=>v.id===id);if(r){playback.stop();void playback.play(r.startMs,r.endMs,false)}}} voices={voices} onManageVoices={() => onNavigate('voices')} /></div></> : <div className="wave-empty"><div className="wave-empty-mark">Audio</div><h1>Your story starts here</h1><p>Record here or drop audio into Wave Studio.<br />Shape your narration, mark voices and add sound effects.</p><div><button className="primary" disabled={w.busy || !hasBackend()} onClick={() => void openProduction('record')}>Record here</button><button disabled={w.busy || !hasBackend()} onClick={() => void openProduction('speech')}>Generate speech</button><button disabled={w.busy || !hasBackend()} onClick={() => void importFile()}>Import audio</button><button disabled={w.busy || !hasBackend()} onClick={() => void showProjects()}>Open recent project</button></div><small>WAV  /  MP3  /  M4A  /  AAC  /  FLAC</small><button className="wave-empty-link" onClick={() => onNavigate('voice-memos')}>Record a voice memo</button></div>}
 {help&&<div className="wave-dialog-backdrop"><StudioModal title="Keyboard shortcuts" onClose={()=>setHelp(false)}><h2>Keyboard shortcuts</h2><p>Space  -  Play / stop</p><p>Shift + Space  -  Play selected fragment or range</p><p>Left / Right or &lt; / &gt;  -  Previous / next fragment; next at the last fragment goes to its end</p><p>Control or Command + Left / Right  -  Selected fragment start / end</p><p>Shift + Left / Right  -  Skip five seconds</p><p>S  -  Split  /  + / -  -  Zoom  /  0  -  Fit</p><p>Shift-click  -  Add to selection  /  Command-click  -  Toggle selection</p><p>Double-click  -  Select whole fragment</p><button onClick={()=>setHelp(false)}>Close</button></StudioModal></div>}
 {joinChoices&&<div className="wave-dialog-backdrop"><StudioModal title="Join voice" onClose={()=>setJoinChoices(null)}><h2>Choose a voice for the joined fragment</h2><p>These fragments have different voice tags. Assign one tag to the joined passage. Generate the voice afterwards to change its sound.</p>{voices.filter(v=>joinChoices.includes(v.id)).map(v=><button key={v.id} onClick={()=>void join(v.id)}>{v.name}</button>)}<button onClick={()=>void join(null)}>Clear voice tags</button><button onClick={()=>setJoinChoices(null)}>Cancel</button></StudioModal></div>}
 {pendingImport&&<div className="wave-dialog-backdrop"><WaveAudioImportPanel path={pendingImport} playheadMs={w.view.playheadMs} endMs={duration} busy={w.busy} onClose={()=>setPendingImport(null)} onAdd={(mode,at)=>{const path=pendingImport;setPendingImport(null);void w.importAudio('file',path,mode,at)}}/></div>}
 {projects&&<div className="wave-dialog-backdrop"><WaveProjectsPanel onClose={()=>setProjects(false)}/></div>}
 {exportPanel&&<div className="wave-dialog-backdrop"><WaveExportPanel onClose={()=>setExportPanel(false)} onJob={id=>{setJob(null);setJobId(id)}}/></div>}

 {recordPanel&&w.project&&<div className="wave-dialog-backdrop"><WaveRecordingPanel projectId={w.project.id} key={w.project.id} onRecorded={async id=>{const projectId=w.project!.id,source=await waveApi.import('memo',null,id);if(latest.current.project?.id!==projectId)throw new Error('Project changed. Reopen the recording project to continue.');latest.current.addSource(source,undefined,'main')}} onClose={()=>setRecordPanel(false)}/></div>}
 {productionKind&&w.project&&<div className="wave-dialog-backdrop"><WaveProductionPanel key={`${w.project.id}-${productionKind}`} kind={productionKind} regionId={productionRegion} voices={voices} onClose={()=>setProductionKind(null)}/></div>}
 </div>
}
