import { invoke } from './platform'
import type { PeakWindow } from '../../shared/audio'
import type { SfxAsset, WaveProject, WaveSource, WaveProcessingResult, WaveVideo } from '../../shared/waveStudio'
export const waveApi = {
 operationStatus:(requestId:string)=>invoke<{id:string;label:string;progress:number}|null>('wave_operation_status',{requestId}),
 cancelOperation:(requestId:string)=>invoke<void>('wave_cancel_operation',{requestId}),
 hasVideo: (path:string)=>invoke<boolean>('wave_has_video',{path}),
 importVideo: (path:string,requestId:string|null=null)=>invoke<WaveVideo>('wave_import_video',{path,requestId}),
 videoUrl:(id:string)=>invoke<string>('wave_video_url',{id}),
 purge:(id:string|null=null)=>invoke<number>('wave_purge',{id}),
 reveal:(id:string,deleted=false)=>invoke<void>('wave_reveal',{id,deleted}),
 deleted:()=>invoke<WaveProject[]>('wave_deleted'),
 delete:(id:string,restore=false)=>invoke<void>('wave_delete',{id,restore}),
 saveCopy:(project:WaveProject,path:string,includeVideo=false)=>invoke<void>('wave_save_copy',{project,path,includeVideo}),
 openCopy:(path:string)=>invoke<WaveProject>('wave_open_copy',{path}),
 normalize: (project: WaveProject, clipId: string) => invoke<number>('wave_normalize', { project, clipId }),
 join: (project: WaveProject, clipIds: string[]) => invoke<WaveSource>('wave_join', { project, clipIds }),
 generateSpeech: (text: string, voiceId: string, projectId: string, revision: number) => invoke<string>('wave_generate_speech', { text, voiceId, projectId, revision }),
 convertRegions: (project: WaveProject, regionIds: string[], regenerate = false) => invoke<string>('wave_convert_regions', { project, regionIds, regenerate }),
 processingResult: (jobId: string) => invoke<WaveProcessingResult>('wave_processing_result', { jobId }),
 exportBundle:(project:WaveProject,path:string,includeVideo=false)=>invoke<void>("wave_export_bundle",{project,path,includeVideo}),
 importBundle:(path:string,requestId?:string)=>invoke<WaveProject>("wave_import_bundle",{path,requestId}),
 list: () => invoke<WaveProject[]>('wave_list'),
 get: (id: string) => invoke<WaveProject>('wave_get', { id }),
 create: (name: string) => invoke<WaveProject>('wave_create', { name }),
 save: (project: WaveProject, expectedRevision: number) => invoke<WaveProject>('wave_save', { project, expectedRevision }),
 import: (kind: 'file' | 'memo' | 'sound', path: string | null = null, id: string | null = null, requestId:string|null=null) => invoke<WaveSource>('wave_import', { kind, path, id, requestId }),
 cancelPeaks: (requestId:string) => invoke<void>('wave_cancel_peaks',{requestId}),
 peaks: (sourceId: string, startMs: number, endMs: number, maxPeaks: number, requestId?: string) => invoke<PeakWindow>('wave_peaks', { requestId, sourceId, startMs: Math.max(0, Math.floor(startMs)), endMs: Math.ceil(endMs), maxPeaks: Math.min(2048, Math.max(1, Math.floor(maxPeaks))) }),
 cancelPreview: () => invoke<void>('wave_cancel_preview'),
 preview: (project: WaveProject, startMs: number, endMs: number) => invoke<ArrayBuffer>('wave_preview', { project, startMs, endMs }),
 export: (project: WaveProject, outputPath: string, videoId: string|null=null, videoTimeline=false, lengthMode:'longest'|'shortest'|null=null) => invoke<string>('wave_export', { project, outputPath, videoId, videoTimeline, lengthMode }),
 sfx: () => invoke<SfxAsset[]>('wave_sfx_list'),
 addSfx: (source: WaveSource, category: string) => invoke<SfxAsset[]>('wave_sfx_add', { source, category }),
 updateSfx: (id: string, name: string, category: string, remove = false) => invoke<SfxAsset[]>('wave_sfx_update', { id, name, category, delete: remove }),
 url: (sourceId: string) => invoke<string>('wave_source_url', { sourceId })
}
