import { describe, expect, it } from 'vitest'
import { blankTimeline, clipDuration, clipEnd, formatWaveTime, sourceClip, timelineDuration } from '../src/shared/waveStudio'
import { assignVoice, changeSpeed, historyEdit, historyRedo, historyUndo, insertSilence, moveClip, removeRange, splitAt } from '../src/shared/waveStudioEdits'
const source = { id: crypto.randomUUID(), name: 'Narration', durationMs: 10000, channels: 2 }
const original = () => ({ ...blankTimeline(), clips: [sourceClip(source)] })
describe('Wave Studio reversible editing', () => {
 it('splits at the correct source sample without modifying the original', () => { const t = original(), result = splitAt(t, 2500); expect(t.clips).toHaveLength(1); expect(result.clips.map(c => [c.startMs,c.sourceStartMs,c.sourceEndMs])).toEqual([[0,0,2500],[2500,2500,10000]]) })
 it('distinguishes ripple deletion from replacing with silence', () => { const t = original(); expect(timelineDuration(removeRange(t,2000,4000))).toBe(8000); const silent=removeRange(t,2000,4000,true); expect(timelineDuration(silent)).toBe(10000); expect(silent.clips.find(c=>!c.sourceId)?.sourceEndMs).toBe(2000) })
 it('shifts sound effects and voice ranges when inserting silence', () => { const t=assignVoice(original(),3000,5000,{id:'voice',name:'Narrator'}); t.sfx=[sourceClip({...source,durationMs:500},4000,true)]; const next=insertSilence(t,2000,500); expect(next.sfx[0]?.startMs).toBe(4500); expect(next.voices[0]?.startMs).toBe(3500); expect(timelineDuration(next)).toBe(10500) })
 it('preserves source intervals and maps annotations when changing selected speed', () => { const t=assignVoice(original(),2000,4000,{id:'voice',name:'Narrator'}); const next=changeSpeed(t,2000,4000,1.08); expect(timelineDuration(next)).toBeCloseTo(8000+2000/1.08); expect(next.voices[0]?.endMs).toBeCloseTo(2000+2000/1.08); expect(next.clips[1]?.sourceEndMs).toBe(4000) })
 it('does not overwrite later fragments when inserting across a gap', () => { let t=splitAt(splitAt(original(),2000),4000); t.clips[1]!.startMs=3000; t.clips[2]!.startMs=5000; const moved=moveClip(t,t.clips[0]!.id,2500); const ordered=moved.clips; expect(ordered.every((c,i)=>i===0||clipEnd(ordered[i-1]!)<=c.startMs+.01)).toBe(true); expect(ordered.filter(c=>c.sourceId).reduce((sum,c)=>sum+clipDuration(c),0)).toBe(10000); expect(ordered.some(c=>!c.sourceId)).toBe(true) })
 it('swaps unequal fragments explicitly and follows voice annotations', () => { let t=splitAt(original(),2000); t=assignVoice(t,2000,10000,{id:'voice',name:'B'}); const swapped=moveClip(t,t.clips[0]!.id,0,t.clips[1]!.id); expect(swapped.clips[0]?.sourceStartMs).toBe(2000); expect(swapped.voices[0]?.startMs).toBe(0); expect(timelineDuration(swapped)).toBe(10000) })
 it('undoes and redoes exactly, discarding redo after a new edit', () => { const t=original(), h=historyEdit({past:[],present:t,future:[]},insertSilence(t,0,500)); expect(historyUndo(h).present).toEqual(t); expect(historyRedo(historyUndo(h)).present).toEqual(h.present); expect(historyEdit(historyUndo(h),splitAt(t,1000)).future).toEqual([]) })
 it('clamps inherited fades after splitting a short fragment', () => { const t=original(); t.clips[0]!.fadeInMs=5000; expect(splitAt(t,1000).clips[0]?.fadeInMs).toBe(1000) })
 it.each([300000,1800000,3600000,7200000])('edits a %i ms timeline without expanding into samples', length => { const t={...blankTimeline(),clips:[sourceClip({...source,durationMs:length})]}; const next=splitAt(t,length/2); expect(next.clips).toHaveLength(2); expect(timelineDuration(next)).toBe(length) })
 it('formats timestamps to milliseconds',()=>expect(formatWaveTime(3600123)).toBe('01:00:00.123'))
})
