import { Checkbox, StudioSlider } from './StudioControls'
import { useEffect, useRef, useState } from 'react'
export function audioTime(ms: number): string { const s = Math.max(0, ms) / 1000; return `${Math.floor(s / 60)}:${(s % 60).toFixed(1).padStart(4, '0')}` }
export function AudioTransport({ url, durationMs, selection, seekTo, onPosition, playRequest }: { url: string | null; playRequest?: number; durationMs?: number; selection?: [number, number]; seekTo?: number; onPosition?: (ms: number) => void }): JSX.Element {
 const audio=useRef<HTMLAudioElement>(null), pendingSeek=useRef<number|null>(null), selectedPlayback=useRef(false), generation=useRef(0)
 const [measuredDuration,setMeasuredDuration]=useState(0),[playing,setPlaying]=useState(false),[position,setPosition]=useState(0),[rate,setRate]=useState(1),[loop,setLoop]=useState(false),[error,setError]=useState('')
 const duration=durationMs||measuredDuration
 useEffect(()=>{generation.current++;pendingSeek.current=0;selectedPlayback.current=false;setPlaying(false);setPosition(0);setMeasuredDuration(0);setError('');const player=audio.current;return()=>{player?.pause()}},[url])
 function seek(ms:number):void { const p=Math.max(0,duration?Math.min(duration,ms):ms),a=audio.current;pendingSeek.current=p;if(a&&a.readyState>=1){a.currentTime=p/1000;pendingSeek.current=null}setPosition(p);onPosition?.(p) }
 async function start():Promise<void>{const a=audio.current,token=generation.current;if(!a||!url)return;setError('');try{await a.play()}catch{if(token===generation.current)setError('Playback could not start. Press Play to retry.')}}
 useEffect(()=>{if(url&&playRequest){selectedPlayback.current=false;seek(0);void start()}},[url,playRequest])
 useEffect(()=>{if(seekTo!==undefined)seek(seekTo)},[seekTo])
 useEffect(()=>{const pauseOthers=(event:Event):void=>{if(event.target instanceof HTMLAudioElement)document.querySelectorAll('audio').forEach(other=>{if(other!==event.target)other.pause()})};document.addEventListener('play',pauseOthers,true);return()=>document.removeEventListener('play',pauseOthers,true)},[])
 function toggle(fromBeginning=false):void {const a=audio.current;if(!a)return;if(!a.paused){a.pause();return}selectedPlayback.current=!fromBeginning&&!!selection;if(fromBeginning)seek(0);else if(selection&&(position<selection[0]||position>=selection[1]))seek(selection[0]);else if(a.ended)seek(0);void start()}
 return <div className="audio-transport"><audio key={url||'empty'} ref={audio} src={url||undefined} preload="metadata" loop={loop&&!selectedPlayback.current} onLoadedMetadata={()=>{const a=audio.current;if(!a)return;setMeasuredDuration(Number.isFinite(a.duration)?a.duration*1000:0);a.playbackRate=rate;if(pendingSeek.current!==null){a.currentTime=Math.min(pendingSeek.current,Number.isFinite(a.duration)?a.duration*1000:pendingSeek.current)/1000;pendingSeek.current=null}}} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)} onError={()=>{if(url)setError('This audio could not be played.')}} onTimeUpdate={()=>{const a=audio.current;if(!a)return;let p=a.currentTime*1000;if(selectedPlayback.current&&selection&&p>=selection[1]){if(loop){a.currentTime=selection[0]/1000;p=selection[0]}else a.pause()}setPosition(p);onPosition?.(p)}}/>
 <button hidden data-audio-play-beginning disabled={!url} onClick={()=>toggle(true)}>Play from beginning / pause</button><button data-audio-play disabled={!url} onClick={()=>toggle()}>{playing?'Pause':'Play'}</button><button disabled={!url} onClick={()=>{audio.current?.pause();seek(0)}}>Stop</button><button disabled={!url} onClick={()=>seek(0)}>Beginning</button><button disabled={!url} onClick={()=>seek(duration)}>End</button><button disabled={!url} onClick={()=>seek(position-5000)}>-5s</button><button disabled={!url} onClick={()=>seek(position+5000)}>+5s</button>
 <StudioSlider aria-label="Playback position" min={0} max={duration||1} step={10} value={position} onChange={e=>seek(Number(e.target.value))}/><span>{audioTime(position)} / {audioTime(duration)}</span><label>Speed / {rate.toFixed(2)}x<StudioSlider aria-label="Playback speed" min={-100} max={100} step={1} value={rate<=1?(rate-1)*200:(rate-1)*100} onChange={e=>{let n=Number(e.target.value);if(Math.abs(n)<4)n=0;const speed=1+n/(n<0?200:100);setRate(speed);if(audio.current)audio.current.playbackRate=speed}}/></label><label><Checkbox checked={loop} onChange={e=>setLoop(e.target.checked)}/>Loop</label>{error&&<span role="alert">{error}</span>}
 </div>
}
