import {StudioModal} from './StudioModal'
import {useToast} from './StudioToast'
import {StudioSlider} from './StudioControls'
import { useEffect, useRef, useState } from 'react'
import type { RecordingSession, PeakWindow } from '../../../shared/audio'
import { selectedTake } from '../../../shared/audio'
import { audioApi } from '../audioNative'
import { errorMessage } from '../native'
import { AudioProcessingPanel } from './AudioProcessingPanel'
import { AudioTransport, audioTime } from './AudioTransport'
export function AudioEditor({ memo, onChange, onQueued, children, onRecordRange, disabled = false }: { memo: RecordingSession; onChange: (memo: RecordingSession) => void; onQueued: (id: string) => void; disabled?: boolean; onRecordRange?: (range: [number, number]) => void; children?: React.ReactNode }): JSX.Element {
 const [audition, setAudition] = useState<string | null>(null)
 const take = memo.takes.find(t => t.id === audition && t.state !== 'rejected') || selectedTake(memo), [url, setUrl] = useState<string | null>(null), [peaks, setPeaks] = useState<PeakWindow | null>(null), [selection, setSelection] = useState<[number, number]>([0, 0]), [zoom, setZoom] = useState(1), [offset, setOffset] = useState(0), [position, setPosition] = useState(0), [busy, setBusy] = useState(false), [error, setError] = useState(''), [value, setValue] = useState(100), [gain, setGain] = useState(1), [seekTo,setSeekTo]=useState<number | undefined>(undefined)
 useToast(error,'error')
 const [deleteTake,setDeleteTake]=useState<string|null>(null), hovered=useRef<string|null>(null)
 const canvas = useRef<HTMLCanvasElement>(null), anchor = useRef<number | null>(null)
 const duration = take?.durationMs || 0, windowMs = duration / zoom, stop = Math.min(duration, offset + windowMs)
 useEffect(() => { let active = true; setUrl(null); setSelection([0,0]);setPosition(0);setSeekTo(0); setOffset(previous => Math.min(previous,Math.max(0,duration-duration/zoom))); if (take) void audioApi.url(memo.id, take.id).then(v => { if (active) setUrl(v) }).catch(e => { if (active) setError(errorMessage(e)) }); return () => { active = false } }, [memo.id, take?.id, duration])
 useEffect(() => { let active = true; if (take && stop > offset) void audioApi.waveform(memo.id, take.id, Math.floor(offset), Math.ceil(stop)).then(v => { if (active) setPeaks(v) }).catch(e => { if (active) setError(errorMessage(e)) }); else setPeaks(null); return () => { active = false } }, [memo.id, take?.id, offset, stop])
 useEffect(() => { const c = canvas.current; if (!c) return; const width = c.clientWidth || 900; c.width = width * 2; c.height = 240; const g = c.getContext('2d'); if (!g) return; g.clearRect(0, 0, c.width, c.height); g.fillStyle = '#161b22'; g.fillRect(0, 0, c.width, c.height); const x = (ms: number) => (ms - offset) / Math.max(1, windowMs) * c.width; g.fillStyle = '#365b7555'; g.fillRect(x(selection[0]), 0, x(selection[1]) - x(selection[0]), c.height); g.strokeStyle = '#8bd5c4'; g.beginPath(); peaks?.peaks.forEach((p, i) => { const px = i / peaks.peaks.length * c.width; g.moveTo(px, 120 - p[1] * 110); g.lineTo(px, 120 - p[0] * 110) }); g.stroke(); g.strokeStyle = '#fafafa'; g.beginPath(); g.moveTo(x(position), 0); g.lineTo(x(position), c.height); g.stroke() }, [peaks, selection, offset, windowMs, position])
 async function run(task: () => Promise<RecordingSession | string>): Promise<void> { if (disabled) return; setBusy(true); setError(''); try { const result = await task(); if (typeof result === 'string') onQueued(result); else { setAudition(null); onChange(result) } } catch (e) { setError(errorMessage(e)) } finally { setBusy(false) } }
 const point = (e: React.PointerEvent<HTMLCanvasElement>): number => { const rect = e.currentTarget.getBoundingClientRect(); return Math.round(Math.max(0, Math.min(duration, offset + (e.clientX - rect.left) / rect.width * windowMs))) }
 return <section className="audio-editor" tabIndex={0} onKeyDown={e=>{if(e.defaultPrevented||e.repeat||document.querySelector('[role=dialog][aria-modal=true]')||(e.target as HTMLElement).closest('input,textarea,select,[contenteditable=true]'))return;if(e.code==='Space'){e.preventDefault();e.currentTarget.querySelector<HTMLButtonElement>('[data-audio-play-beginning]')?.click()}else if(e.key==='ArrowLeft'||e.key==='ArrowRight'||e.key==='<'||e.key==='>'){e.preventDefault();const takes=memo.takes.filter(t=>t.state!=='rejected'),index=takes.findIndex(t=>t.id===take?.id);setAudition(takes[Math.max(0,Math.min(takes.length-1,index+(e.key==='ArrowRight'||e.key==='>'?1:-1)))]?.id||null)}else if(e.key.toLowerCase()==='u'&&!e.metaKey&&!e.ctrlKey){const t=memo.takes.find(t=>t.id===(hovered.current||take?.id));if(t&&!disabled)void run(()=>audioApi.choose(memo,t.id,t.state==='preview'?'accept':'select'))}else if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();if(!disabled)void run(()=>audioApi.choose(memo,'',e.shiftKey?'redo':'undo'))}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();if(take&&!disabled)setDeleteTake(hovered.current||take.id)}else if(e.key==='Escape'){setSelection([0,0]);anchor.current=null}}}><h3>{take?.name || 'Record or import audio to begin'}</h3><canvas ref={canvas} aria-label="Waveform. Drag to select audio; use start and end fields for keyboard selection." onPointerDown={e => { const p=point(e), tolerance=windowMs*8/(e.currentTarget.clientWidth||900); anchor.current=Math.abs(p-selection[0])<tolerance?selection[1]:Math.abs(p-selection[1])<tolerance?selection[0]:e.shiftKey?selection[0]:p; e.currentTarget.setPointerCapture(e.pointerId); setSelection([Math.min(anchor.current,p),Math.max(anchor.current,p)]);setSeekTo(p) }} onPointerMove={e => { if (anchor.current !== null) { const p = point(e); setSelection([Math.min(anchor.current, p), Math.max(anchor.current, p)]) } }} onPointerUp={() => { anchor.current = null }} onPointerCancel={() => { anchor.current = null }} onWheel={e=>{if(e.ctrlKey||e.metaKey)setZoom(z=>Math.max(1,Math.min(32,z*(e.deltaY>0?.9:1.1))));else setOffset(o=>Math.max(0,Math.min(duration-windowMs,o+e.deltaX+e.deltaY)))}} />
 <div className="audio-tools"><label>Zoom <StudioSlider min={1} max={32} value={zoom} onChange={e => { setZoom(Number(e.target.value)); setOffset(0) }} /></label>{zoom>1&&<label>View <StudioSlider min={0} max={Math.max(0, duration - windowMs)} value={offset} onChange={e => setOffset(Number(e.target.value))} /></label>}<span>{audioTime(offset)}-{audioTime(stop)}</span></div>
 {take?.cues?.length ? <div className="audio-sentences" aria-label="Sentence timing">{take.cues.map(cue=><button key={cue.order} className={position>=cue.startMs&&position<cue.endMs?'selected':''} onClick={()=>setSelection([cue.startMs,cue.endMs])}>{cue.text}</button>)}</div> : null}
 <AudioTransport seekTo={seekTo} url={url} durationMs={duration} selection={selection[1] > selection[0] ? selection : undefined} onPosition={setPosition} />
 <div className="audio-edit-group"><h3>Edit selection</h3><div className="audio-tools audio-edit-fields"><label>Start (s)<input type="number" min={0} max={selection[1] / 1000} step={0.01} value={selection[0] / 1000} onChange={e => setSelection([Math.max(0, Math.min(selection[1], Number(e.target.value) * 1000)), selection[1]])} /></label><label>End (s)<input type="number" min={selection[0] / 1000} max={duration / 1000} step={0.01} value={selection[1] / 1000} onChange={e => setSelection([selection[0], Math.min(duration, Math.max(selection[0], Number(e.target.value) * 1000))])} /></label><label>Amount (ms)<input type="number" min={0} value={value} onChange={e => setValue(Number(e.target.value))} /></label><label>Gain multiplier<input type="number" min={0} max={8} step={0.1} value={gain} onChange={e => setGain(Number(e.target.value))}/></label><div className="audio-tools"><button onClick={() => setSelection([0, duration])}>Select all</button><span>Selected {audioTime(selection[1]-selection[0])}</span><button onClick={()=>{setZoom(1);setOffset(0)}}>Fit</button></div></div>
 <div className="audio-tools">{(['trim', 'delete', 'silence', 'split', 'fade', 'gain', 'insert_silence', 'shorten_silence'] as const).map(kind => <button key={kind} disabled={disabled || busy || !take || take.id !== memo.selectedTakeId || selection[1] <= selection[0]} onClick={() => void run(() => audioApi.edit(memo, { kind, startMs: Math.round(selection[0]), endMs: Math.round(selection[1]), value: kind === 'gain' ? gain : value }))}>{kind.charAt(0).toUpperCase()+kind.slice(1).replaceAll('_', ' ')}</button>)}<button disabled={disabled || busy || !memo.undo.length} onClick={() => void run(() => audioApi.choose(memo, '', 'undo'))}>Undo</button><button disabled={disabled || busy || !memo.redo.length} onClick={() => void run(() => audioApi.choose(memo, '', 'redo'))}>Redo</button></div>
 <div className="audio-tools audio-selection-actions"><button disabled={disabled || busy || !take || take.id !== memo.selectedTakeId || selection[1] <= selection[0]} onClick={() => void run(() => audioApi.extract(memo,Math.round(selection[0]),Math.round(selection[1])))}>Save selection as new memo</button>
 {onRecordRange && <button disabled={disabled || busy || !take || take.id !== memo.selectedTakeId || selection[1] <= selection[0]} onClick={() => onRecordRange(selection)}>Record replacement for selection</button>}
 </div></div>
<h3>Takes</h3><div className="take-list">{memo.takes.filter(t => t.state !== 'rejected' && !memo.takes.some(other => other.id !== t.id && other.composition.clips.some(c => c.assetId === t.id) && t.name === 'Processed selection')).map(t => <div key={t.id} onMouseEnter={()=>{hovered.current=t.id}} onMouseLeave={()=>{hovered.current=null}} onFocus={()=>{hovered.current=t.id}}><button onClick={() => setAudition(t.id)}>{take?.id === t.id ? 'Listening' : 'Listen'}</button><input aria-label="Take name" key={t.id+t.name} defaultValue={t.name} onBlur={e=>{if(e.target.value!==t.name)void run(()=>audioApi.updateTake(memo,t.id,e.target.value,t.notes||'',!!t.favorite))}}/><span className="take-duration">{audioTime(t.durationMs)}</span><button className="take-favorite" aria-label={t.favorite?'Unfavorite take':'Favorite take'} disabled={disabled||busy} onClick={()=>void run(()=>audioApi.updateTake(memo,t.id,t.name,t.notes||'',!t.favorite))}><svg width="16" height="16" viewBox="0 0 24 24" fill={t.favorite?'currentColor':'none'} stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><path d="m12 3 2.8 5.7 6.3.9-4.6 4.5 1.1 6.3L12 17.4l-5.6 3 1.1-6.3L3 9.6l6.2-.9Z"/></svg></button><details><summary>Notes</summary><textarea aria-label="Take notes" key={t.id+t.notes} defaultValue={t.notes||''} onBlur={e=>{if(e.target.value!==(t.notes||''))void run(()=>audioApi.updateTake(memo,t.id,t.name,e.target.value,!!t.favorite))}}/></details><button disabled={disabled||busy} onClick={()=>setDeleteTake(t.id)}>Delete take</button><button disabled={disabled || busy || t.id === memo.selectedTakeId} onClick={() => void run(() => audioApi.choose(memo, t.id, t.state === 'preview' ? 'accept' : 'select'))}>{t.id===memo.selectedTakeId?'In use':t.state === 'preview' ? 'Accept' : 'Use take'}</button>{t.state === 'preview' && <button disabled={busy} onClick={() => void run(() => audioApi.choose(memo, t.id, 'reject'))}>Reject</button>}</div>)}</div> <AudioProcessingPanel memo={memo} selection={selection} disabled={disabled || busy || take?.id !== memo.selectedTakeId} onQueued={onQueued}/>{children}<details><summary>Keyboard shortcuts</summary><p>Left / Right or &lt; / &gt;: audition takes. Space: play from beginning / pause. U: use hovered take. Delete: confirm deletion of hovered or current take.</p></details>{deleteTake&&<StudioModal title="Delete take" onClose={()=>setDeleteTake(null)}><h2>Delete this take?</h2><p>The other takes and original media stay available.</p><button disabled={busy} className="danger" onClick={()=>{const t=memo.takes.find(t=>t.id===deleteTake);if(t)void run(async()=>{const next=await audioApi.updateTake(memo,t.id,t.name,t.notes||'',!!t.favorite,true);setDeleteTake(null);return next})}}>Delete take</button><button onClick={()=>setDeleteTake(null)}>Cancel</button></StudioModal>}</section>
}
