import { Checkbox, Select } from './StudioControls'
import { useEffect, useState } from 'react'
import type { AudioEngine, EngineConfig, EngineStatus, RecordingSession, VoiceProfile } from '../../../shared/audio'
import type { Voice } from '../../../shared/contracts'
import { processorApi } from '../audioNative'
import { errorMessage, isDesktop, productionApi } from '../native'
const names: Record<AudioEngine,string> = {passthrough:'Reference test',seed_vc:'Seed-VC',rvc:'RVC',deepfilternet:'DeepFilterNet',resemble_enhance:'Resemble Enhance'}
export function AudioProcessingPanel({memo,selection,disabled,onQueued}:{memo:RecordingSession;selection:[number,number];disabled:boolean;onQueued:(id:string)=>void}):JSX.Element{
 const [configs,setConfigs]=useState<EngineConfig[]>([]),[engine,setEngine]=useState<AudioEngine>('deepfilternet'),[status,setStatus]=useState<EngineStatus|null>(null),[profiles,setProfiles]=useState<VoiceProfile[]>([]),[voices,setVoices]=useState<Voice[]>([]),[profileId,setProfileId]=useState(''),[preset,setPreset]=useState('Quick Clean'),[preprocess,setPreprocess]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[setupPython,setSetupPython]=useState(''),[params,setParams]=useState('{}'),[crossfade,setCrossfade]=useState(30)
 const config=configs.find(c=>c.engine===engine),profile=profiles.find(p=>p.id===profileId),convert=engine==='seed_vc'||engine==='rvc'
 useEffect(()=>{if(isDesktop())void Promise.all([processorApi.configs(),processorApi.profiles(),productionApi.voices()]).then(([c,p,v])=>{setConfigs(c);setProfiles(p);setVoices(v)}).catch(e=>setError(errorMessage(e)))},[])
 useEffect(()=>{let active=true;setStatus(null);if(config)void processorApi.status(config).then(s=>{if(active)setStatus(s)}).catch(e=>{if(active)setError(errorMessage(e))});return()=>{active=false}},[engine,configs.length])
 async function run(task:()=>Promise<void>):Promise<void>{setError('');setBusy(true);try{await task()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 const patch=(key:keyof EngineConfig,value:unknown):void=>{setStatus(null);setConfigs(cs=>cs.map(c=>c.engine===engine?{...c,[key]:value}:c))}
 async function saveProfile(p:VoiceProfile):Promise<void>{const result=await processorApi.saveProfile(p);setProfiles(ps=>ps.map(v=>v.id===result.id?result:v))}
 return <section className="audio-processing"><h3>Voice conversion & cleanup</h3>{error&&<p role="alert">{error}</p>}<div className="audio-tools"><details><summary>Choose conversion or custom engine</summary><label>Engine<Select value={engine} onChange={e=>{setEngine(e.target.value as AudioEngine);setPreset('Custom')}}>{Object.entries(names).map(([id,label])=><option key={id} value={id}>{label}</option>)}</Select></label></details><label>Quality<Select value={preset} onChange={e=>{setPreset(e.target.value);if(e.target.value==='Quick Clean')setEngine('deepfilternet');if(e.target.value==='Studio Quality')setEngine('resemble_enhance')}}><option>Original</option><option>Quick Clean</option><option>Studio Quality</option><option>Custom</option></Select></label><label>Voice profile<Select value={profileId} onChange={e=>setProfileId(e.target.value)}><option value="">Choose profile</option>{voices.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</Select></label><label>Boundary crossfade (ms)<input type="number" min={0} max={1000} value={crossfade} onChange={e=>setCrossfade(Number(e.target.value))}/></label>{(convert||engine==='resemble_enhance')&&<label><Checkbox checked={preprocess} onChange={e=>setPreprocess(e.target.checked)}/>Clean source with DeepFilterNet first</label>}</div>
 <p>{preset==='Original'?'Original audio; no cleanup applied.':status?.ready?`Ready · ${status.backend}`:status?.message||'Checking local engine…'}{status?.missingFiles.length?` Missing: ${status.missingFiles.join(', ')}`:''}</p>
 <button disabled={preset==='Original'||disabled||busy||!status?.ready||selection[1]<=selection[0]||(convert&&!profileId)} onClick={()=>void run(async()=>{const parameters:unknown=JSON.parse(params);if(!parameters||typeof parameters!=='object'||Array.isArray(parameters))throw new Error('Parameters must be a JSON object.');onQueued(await processorApi.process({memoId:memo.id,expectedRevision:memo.revision,engine,operation:convert?'convert':engine==='deepfilternet'?'denoise':'enhance',preset,profileId:profileId||null,startMs:Math.round(selection[0]),endMs:Math.round(selection[1]),crossfadeMs:crossfade,params:{...(preset==='Studio Quality'?{nfe:64,diffusionSteps:60,attenuation:24}:{nfe:16,diffusionSteps:20,attenuation:12}),...parameters},preprocess}))})}>Preview {convert?'conversion':'cleanup'} of selection</button>
 <details><summary>Local engine setup</summary>{config&&<><p>Choose an existing Python environment and local model folder, or explicitly install dependencies below. Inference uses local models. Large model files are supplied separately.</p><label>Environment Python<input value={config.pythonPath||''} placeholder="Use the app's isolated environment" onChange={e=>patch('pythonPath',e.target.value||null)}/></label><label>Model / engine checkout folder<input value={config.modelDir||''} onChange={e=>patch('modelDir',e.target.value||null)}/></label><label>Backend<Select value={config.backend} onChange={e=>patch('backend',e.target.value)}><option value="auto">Automatic</option><option value="cpu">CPU</option><option value="mps">Apple GPU, where supported</option></Select></label><button disabled={busy||disabled} onClick={()=>void run(async()=>{await processorApi.saveConfig(config);setStatus(await processorApi.status(config))})}>Save & check readiness</button><label>Base Python 3.10 / 3.11 for installation<input value={setupPython} onChange={e=>setSetupPython(e.target.value)}/></label><button disabled={busy||disabled||!setupPython||engine==='passthrough'} onClick={()=>void run(async()=>onQueued(await processorApi.setup(engine,setupPython)))}>Install isolated Python dependencies</button><label>Advanced parameters (JSON)<textarea value={params} onChange={e=>setParams(e.target.value)}/></label></>}</details>
 {profile&&<details><summary>Voice profile references & models</summary><p>Existing Chatterbox voices keep their samples. Add the accepted memo as a conversion reference; reference samples should be clean and contain one speaker.</p><label>Notes<textarea key={profile.id+profile.updatedAtMs} defaultValue={profile.notes} onBlur={e=>void run(()=>saveProfile({...profile,notes:e.target.value}))}/></label><button disabled={busy||disabled||!memo.selectedTakeId} onClick={()=>void run(()=>saveProfile({...profile,referenceMemoIds:[...new Set([...profile.referenceMemoIds,memo.id])],selectedReferenceMemoId:memo.id}))}>Use this memo as reference</button><label>Selected reference<Select value={profile.selectedReferenceMemoId||''} onChange={e=>void run(()=>saveProfile({...profile,selectedReferenceMemoId:e.target.value||null}))}><option value="">Chatterbox selected sample</option>{profile.referenceMemoIds.map(id=><option key={id} value={id}>{id===memo.id?memo.name:id}</option>)}</Select></label><label>RVC model file<input key={'model'+profile.id+profile.updatedAtMs} defaultValue={profile.modelPath||''} onBlur={e=>{if(e.target.value!==(profile.modelPath||''))void run(()=>saveProfile({...profile,modelPath:e.target.value||null}))}}/></label><label>Optional RVC index file<input key={'index'+profile.id+profile.updatedAtMs} defaultValue={profile.indexPath||''} onBlur={e=>{if(e.target.value!==(profile.indexPath||''))void run(()=>saveProfile({...profile,indexPath:e.target.value||null}))}}/></label></details>}
 </section>
}
