import { useEffect, useState } from 'react'
import type { Voice } from '../../../shared/contracts'
import { errorMessage, productionApi } from '../native'
export function VoiceMetadataEditor({ voice, onSaved }: { voice: Voice; onSaved: () => Promise<void> }): JSX.Element {
 const [editing, setEditing] = useState(false), [name, setName] = useState(voice.name), [color, setColor] = useState(voice.color || '#718392'), [notes, setNotes] = useState(voice.notes || ''), [provider, setProvider] = useState(voice.provider || 'chatterbox_turbo'), [error, setError] = useState(''), [busy, setBusy] = useState(false)
 useEffect(()=>{if(!editing){setName(voice.name);setColor(voice.color||'#718392');setNotes(voice.notes||'');setProvider(voice.provider||'chatterbox_turbo')}},[voice,editing])
 if (voice.builtIn) return <span className="wave-color-dot" style={{ background: color }} />
 return <div className="voice-metadata"><span aria-label="Voice color" className="wave-color-dot" style={{background:color}}/><button onClick={() => setEditing(!editing)}>{editing ? 'Close voice details' : 'Edit name, color & notes'}</button>{editing && <form onSubmit={e => { e.preventDefault(); setBusy(true); setError(''); void productionApi.updateVoice({ ...voice, name, color, notes, provider }).then(onSaved).then(() => setEditing(false)).catch(e => setError(errorMessage(e))).finally(() => setBusy(false)) }}><label>Voice name<input maxLength={80} required value={name} onChange={e => setName(e.target.value)} /></label><label>Timeline color<input type="color" value={color} onChange={e => setColor(e.target.value)} /></label><label>Notes<textarea maxLength={4000} value={notes} onChange={e => setNotes(e.target.value)} /></label><label>Speech model<select value={provider} onChange={e => setProvider(e.target.value)}><option value="chatterbox_turbo">Chatterbox Turbo</option><option value="chatterbox_original">Original Chatterbox</option></select></label>{error && <p role="alert">{error}</p>}<button disabled={busy || !name.trim()} type="submit">Save voice</button></form>}</div>
}
