import { useEffect, useRef, useState, type PointerEvent } from 'react'
import { clipEnd, formatWaveTime, timelineDuration, type WaveClip, type WaveTimeline, type WaveView } from '../../../shared/waveStudio'
import { moveClip, transferClip } from '../../../shared/waveStudioEdits'
import { WaveformCanvas } from './WaveformCanvas'
interface Props { timeline: WaveTimeline; view: WaveView; setView: React.Dispatch<React.SetStateAction<WaveView>>; edit: (t: WaveTimeline) => void; onSeek: (ms: number) => void; onSfxDrop: (id: string, at: number, lane?: 'main' | 'sfx') => void; onError: (message: string) => void }
interface Drag { mode: 'select' | 'selection-start' | 'selection-end' | 'clip' | 'sfx' | 'voice-start' | 'voice-end' | 'silence-resize'; start: number; pointerX: number; pointerY: number; id: string; original: WaveTimeline; offset: number; moved: boolean; originView: WaveView }
export function WaveStudioTimeline({ timeline, view, setView, edit, onSeek, onSfxDrop, onError }: Props): JSX.Element {
 const ref = useRef<HTMLDivElement>(null), drag = useRef<Drag | null>(null), [width, setWidth] = useState(800), [preview, setPreview] = useState<WaveTimeline | null>(null), [feedback, setFeedback] = useState(''), [dropAt, setDropAt] = useState<number | null>(null)
 const previewRef = useRef<WaveTimeline | null>(null)
 const updatePreview = (value: WaveTimeline | null) => { previewRef.current = value; setPreview(value) }
 const duration = timelineDuration(timeline), shown = preview ?? timeline
 const x = (ms: number) => (ms - view.offsetMs) / view.spanMs * width
 const ms = (clientX: number) => Math.max(0, view.offsetMs + (clientX - (ref.current?.getBoundingClientRect().left || 0)) / width * view.spanMs)
 const snap = (at: number, ignored = '') => { const threshold = view.spanMs / width * 7, candidates = [0, view.playheadMs, ...timeline.clips.filter(c => c.id !== ignored).flatMap(c => [c.startMs, clipEnd(c)]), ...(view.selection || [])]; const near = candidates.find(t => Math.abs(t - at) < threshold); if (near !== undefined) { setFeedback(`Snap · ${formatWaveTime(near)}`); return near } return at }
 useEffect(() => { if (!ref.current) return; const observer = new ResizeObserver(() => setWidth(ref.current!.clientWidth)); observer.observe(ref.current); return () => observer.disconnect() }, [])
 useEffect(() => { const element = ref.current; if (!element) return; const wheel = (e: WheelEvent) => { e.preventDefault(); if (e.metaKey || e.ctrlKey) { const anchor = ms(e.clientX), ratio = (e.clientX - element.getBoundingClientRect().left) / width; setView(v => { const spanMs = Math.max(250, Math.min(86400000, v.spanMs * Math.exp(e.deltaY * .003))); return { ...v, spanMs, offsetMs: Math.max(0, anchor - ratio * spanMs) } }) } else { setView(v => ({ ...v, offsetMs: Math.max(0, Math.min(Math.max(0, duration - v.spanMs * .05), v.offsetMs + (Math.abs(e.deltaX) > Math.abs(e.deltaY) ? e.deltaX : e.deltaY) / width * v.spanMs)) })) } }; element.addEventListener('wheel', wheel, { passive: false }); return () => element.removeEventListener('wheel', wheel) }, [width, view.offsetMs, view.spanMs, duration])
 function down(e: PointerEvent<HTMLElement>, lane: 'main' | 'sfx' | 'voice', explicit?: string, regionId?: string): void {
   if (e.button !== 0) return
   const at = ms(e.clientX), list = lane === 'sfx' ? timeline.sfx : timeline.clips, c = [...list].reverse().find(c => at >= c.startMs && at <= clipEnd(c)), v = lane === 'voice' ? timeline.voices.find(v => regionId ? v.id === regionId : at >= v.startMs && at < v.endMs) : null
   let mode: Drag['mode'] = 'select', id = '', offset = 0
   if (lane === 'voice' && v) { setView(s => ({ ...s, selectedId: v.id })); id = v.id; if (explicit === 'start') mode = 'voice-start'; else if (explicit === 'end') mode = 'voice-end'; else return }
   else if (explicit === 'selection-start') mode = 'selection-start'
   else if (explicit === 'selection-end') mode = 'selection-end'
   else if (c && lane === 'sfx') { mode = 'sfx'; id = c.id; offset = at - c.startMs; setView(s => ({ ...s, selectedId: id })) }
   else if (c && (e.altKey || (c.sourceId && e.clientY - e.currentTarget.getBoundingClientRect().top < 24))) { mode = 'clip'; id = c.id; offset = at - c.startMs; setView(s => ({ ...s, selectedId: id })) }
   else if (c && !c.sourceId && Math.abs(x(clipEnd(c)) - (e.clientX - ref.current!.getBoundingClientRect().left)) < 9) { mode = 'silence-resize'; id = c.id }
   else { setView(s => ({ ...s, selectedId: c?.id || null, selection: null })); onSeek(Math.min(at, duration)) }
   drag.current = { mode, start: at, pointerX: e.clientX, pointerY: e.clientY, id, original: timeline, offset, moved: false, originView: view }; e.currentTarget.setPointerCapture(e.pointerId)
 }
 function motion(e: PointerEvent<HTMLElement>): void {
   const d = drag.current; if (!d) return
   if (Math.abs(e.clientX - d.pointerX) < 3 && Math.abs(e.clientY-d.pointerY)<3 && !d.moved) return; d.moved = true
   const at = snap(ms(e.clientX), d.id), selectedAt = Math.min(duration, at); setDropAt(null)
   if (d.mode === 'select') setView(v => { const start = Math.min(duration, d.start, selectedAt), end = Math.min(duration, Math.max(d.start, selectedAt)); return { ...v, selection: end > start ? [start, end] : null } })
   else if (d.mode === 'selection-start' || d.mode === 'selection-end') setView(v => { const s = d.originView.selection; if (!s) return v; return { ...v, selection: d.mode === 'selection-start' ? [Math.max(0, Math.min(selectedAt, s[1] - 1)), s[1]] : [s[0], Math.min(duration, Math.max(selectedAt, s[0] + 1))] } })
   else if (d.mode === 'clip' && e.clientY >= (ref.current?.querySelector('.wave-sfx-lane')?.getBoundingClientRect().top ?? Infinity)) updatePreview(transferClip(d.original,d.id,'sfx',Math.max(0,at-d.offset)))
   else if (d.mode === 'clip') { const swap = e.shiftKey ? d.original.clips.find(c => c.id !== d.id && at >= c.startMs && at < clipEnd(c)) : undefined; setFeedback(swap ? `Swap with ${swap.name}` : 'Insert / move fragment · Shift to swap'); setDropAt(at - d.offset); updatePreview(moveClip(d.original, d.id, snap(Math.max(0, at - d.offset), d.id), swap?.id)) }
   else if (d.mode === 'sfx' && e.clientY < (ref.current?.querySelector('.wave-sfx-lane')?.getBoundingClientRect().top ?? 0)) { setFeedback('Insert into narration'); updatePreview(transferClip(d.original,d.id,'main',Math.max(0,at-d.offset))) }
   else if (d.mode === 'sfx') updatePreview({ ...d.original, sfx: d.original.sfx.map(c => c.id === d.id ? { ...c, startMs: snap(Math.max(0, at - d.offset), d.id) } : c) })
   else if (d.mode === 'silence-resize') { const c = d.original.clips.find(c => c.id === d.id)!; const end = Math.max(c.startMs + 1, at), delta = end - clipEnd(c); updatePreview({ ...d.original, clips: d.original.clips.map(c2 => c2.id === c.id ? { ...c2, sourceEndMs: c2.sourceStartMs + (end - c2.startMs) * c2.speed } : c2.startMs >= clipEnd(c) ? { ...c2, startMs: c2.startMs + delta } : c2), sfx: d.original.sfx.map(s => s.startMs >= clipEnd(c) ? { ...s, startMs: s.startMs + delta } : s), voices: d.original.voices.map(v => ({ ...v, startMs: v.startMs >= clipEnd(c) ? v.startMs + delta : v.startMs, endMs: v.endMs >= clipEnd(c) ? v.endMs + delta : v.endMs })) }) }
   else updatePreview({ ...d.original, voices: d.original.voices.map(v => v.id === d.id ? d.mode === 'voice-start' ? { ...v, startMs: Math.min(at, v.endMs - 1) } : { ...v, endMs: Math.min(duration, Math.max(at, v.startMs + 1)) } : v) })
 }
 function finish(e: PointerEvent<HTMLElement>): void { if (drag.current?.moved && previewRef.current) edit(previewRef.current); drag.current = null; updatePreview(null); setFeedback(''); setDropAt(null); if (e.currentTarget.hasPointerCapture(e.pointerId)) e.currentTarget.releasePointerCapture(e.pointerId) }
 const step = [100, 250, 500, 1000, 2000, 5000, 10000, 30000, 60000, 300000, 600000, 1800000, 3600000].find(n => n / view.spanMs * width > 80) || 3600000
 const ticks = Array.from({ length: Math.ceil(view.spanMs / step) + 1 }, (_, i) => Math.ceil(view.offsetMs / step) * step + i * step)
 const laneHandlers = (lane: 'main' | 'sfx' | 'voice') => ({ onPointerDown: (e: PointerEvent<HTMLElement>) => down(e, lane), onPointerMove: motion, onPointerUp: finish, onPointerCancel: () => { drag.current = null; updatePreview(null); setFeedback('') } })
 return <section className="wave-timeline-wrap"><div className="wave-lane-titles"><span>Voices</span><span>Narration</span><span>Sound effects</span></div><div className="wave-timeline" ref={ref}>
   <div className="wave-ruler" onPointerDown={e => onSeek(Math.min(duration, ms(e.clientX)))}>{ticks.map(t => <span key={t} style={{ left: x(t) }}>{formatWaveTime(t)}</span>)}</div>
   <div className="wave-voice-lane" {...laneHandlers('voice')}>{shown.voices.filter(v => v.startMs < view.offsetMs + view.spanMs && v.endMs > view.offsetMs).slice(0, 200).map(v => <div key={v.id} className={`wave-voice-region ${view.selectedId === v.id ? 'selected' : ''}`} style={{ left: x(v.startMs), width: Math.max(2, x(v.endMs) - x(v.startMs)), backgroundColor: v.color }}><span className="wave-edge" onPointerDown={e => { e.stopPropagation(); down(e, 'voice', 'start', v.id) }} /><span>{v.name}</span><span className="wave-edge end" onPointerDown={e => { e.stopPropagation(); down(e, 'voice', 'end', v.id) }} /></div>)}</div>
   <div className="wave-main-lane" onDragOver={e=>{e.preventDefault();setDropAt(ms(e.clientX))}} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('application/homer-sfx');if(id)onSfxDrop(id,ms(e.clientX),'main');setDropAt(null)}} {...laneHandlers('main')}><WaveformCanvas clips={shown.clips} view={view} height={280} selectedId={view.selectedId} onError={onError} />{view.selection && <div className="wave-selection" style={{ left: x(view.selection[0]), width: x(view.selection[1]) - x(view.selection[0]) }}><button aria-label="Selection start" onPointerDown={e => { e.stopPropagation(); down(e as unknown as PointerEvent<HTMLElement>, 'main', 'selection-start') }} /><button aria-label="Selection end" onPointerDown={e => { e.stopPropagation(); down(e as unknown as PointerEvent<HTMLElement>, 'main', 'selection-end') }} /></div>}</div>
   <div className="wave-sfx-lane" {...laneHandlers('sfx')} onDragOver={e => { e.preventDefault(); setDropAt(snap(ms(e.clientX))); setFeedback(`Place sound effect · ${formatWaveTime(ms(e.clientX))}`) }} onDragLeave={() => { setDropAt(null); setFeedback('') }} onDrop={e => { e.preventDefault(); const id = e.dataTransfer.getData('application/homer-sfx'); if (id) onSfxDrop(id, snap(ms(e.clientX))); setDropAt(null); setFeedback('') }}><WaveformCanvas clips={shown.sfx} view={view} height={110} selectedId={view.selectedId} onError={onError} />{!shown.sfx.length && <span className="wave-sfx-placeholder">Drag a sound here or choose Add SFX</span>}</div>
   <div className="wave-playhead" style={{ left: x(view.playheadMs) }} /><div className="wave-drop-line" style={{ display: dropAt === null ? 'none' : 'block', left: x(dropAt || 0) }} />
 </div><footer><span>{view.selection ? `${formatWaveTime(view.selection[0])} — ${formatWaveTime(view.selection[1])} · ${((view.selection[1] - view.selection[0]) / 1000).toFixed(3)}s selected` : 'Drag to select · Option-drag to move a fragment · Shift while moving to swap'}</span><span role="status">{feedback}</span></footer><input className="wave-scroll" aria-label="Timeline position" type="range" min={0} max={Math.max(0, duration - view.spanMs)} step={1} value={Math.min(view.offsetMs, Math.max(0, duration - view.spanMs))} onChange={e => setView(v => ({ ...v, offsetMs: Number(e.target.value) }))} /></section>
}
