import {placeVideo,videoHolds} from '../../../shared/waveStudio'
import { StudioSlider } from './StudioControls'
import { useEffect, useRef, useState, type PointerEvent } from 'react'
import { clipEnd, formatWaveTime, timelineDuration, type WaveClip, type WaveTimeline, type WaveView, type WaveVideo } from '../../../shared/waveStudio'
import { moveClip, transferClip, packSfxRows, trimSoundtrack, trimVideo } from '../../../shared/waveStudioEdits'
import { WaveformCanvas } from './WaveformCanvas'
interface Props { sources: {id:string;durationMs:number}[]; videos:WaveVideo[];setVideos:(v:WaveVideo[])=>void;durationMs:number; timeline: WaveTimeline; view: WaveView; setView: React.Dispatch<React.SetStateAction<WaveView>>; edit: (t: WaveTimeline) => void; onSeek: (ms: number) => void; onSfxDrop: (id: string, at: number, lane?: 'main' | 'sfx') => void; onError: (message: string) => void }
interface Drag { mode: 'select' | 'selection-start' | 'selection-end' | 'clip' | 'sfx' | 'voice-start' | 'voice-end' | 'silence-resize' | 'sfx-start' | 'sfx-end' | 'main-start' | 'main-end'; start: number; pointerX: number; pointerY: number; id: string; original: WaveTimeline; offset: number; moved: boolean; originView: WaveView }
export function WaveStudioTimeline({ sources, videos, setVideos, durationMs, timeline, view, setView, edit, onSeek, onSfxDrop, onError }: Props): JSX.Element {
 const ref = useRef<HTMLDivElement>(null), drag = useRef<Drag | null>(null), [width, setWidth] = useState(800), [preview, setPreview] = useState<WaveTimeline | null>(null), [feedback, setFeedback] = useState(''), [dropAt, setDropAt] = useState<number | null>(null)
 const previewRef = useRef<WaveTimeline | null>(null)
 const updatePreview = (value: WaveTimeline | null) => { previewRef.current = value; setPreview(value) }
 const duration = Math.max(durationMs,timelineDuration(timeline)), shown = preview ?? timeline
 const rowPositions=useRef(new Map<string,number>())
 const sfxRows = packSfxRows(shown.sfx,rowPositions.current)
 sfxRows.forEach((row,i)=>row.forEach(c=>rowPositions.current.set(c.id,i)))
 const x = (ms: number) => (ms - view.offsetMs) / view.spanMs * width
 const ms = (clientX: number) => Math.max(0, view.offsetMs + (clientX - (ref.current?.getBoundingClientRect().left || 0)) / width * view.spanMs)
 const videoDrag=useRef<{id:string;edge?:'start'|'end';offset:number;original:WaveVideo[];moved:boolean;x:number}|null>(null)
 const [videoPreview,setVideoPreview]=useState<WaveVideo[]|null>(null),videoPreviewRef=useRef<WaveVideo[]|null>(null)
 const shownVideos=videoPreview??videos
 function videoDown(e:PointerEvent<HTMLElement>,v:WaveVideo,edge?:'start'|'end'):void {
  if(e.button!==0)return;e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId)
  videoDrag.current={id:v.id,edge,offset:ms(e.clientX)-v.startMs,original:videos,moved:false,x:e.clientX}
  setView(s=>({...s,selectedId:v.id,selectedIds:[v.id],selection:null}))
 }
 function videoMotion(e:PointerEvent<HTMLElement>):void {
  const d=videoDrag.current;if(!d||Math.abs(e.clientX-d.x)<3&&!d.moved)return;d.moved=true
  const v=d.original.find(v=>v.id===d.id)!
  try{const next=d.edge?trimVideo(d.original,d.id,d.edge,ms(e.clientX)):d.original.map(n=>n.id===v.id?{...n,startMs:placeVideo(d.original,v.durationMs,ms(e.clientX)-d.offset,v.id)}:n);videoPreviewRef.current=next;setVideoPreview(next);setFeedback(d.edge?'Adjust video source range':'Move video')}catch{setFeedback('No free space within the timeline.')}
 }
 function videoFinish(e:PointerEvent<HTMLElement>,cancel=false):void {
  if(!cancel&&videoDrag.current?.moved&&videoPreviewRef.current)setVideos(videoPreviewRef.current)
  videoDrag.current=null;videoPreviewRef.current=null;setVideoPreview(null);setFeedback('');if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)
 }
 const snap = (at: number, ignored = '') => { const threshold = view.spanMs / width * 7, candidates = [0, view.playheadMs, ...timeline.clips.filter(c => c.id !== ignored).flatMap(c => [c.startMs, clipEnd(c)]), ...(view.selection || [])]; const near = candidates.find(t => Math.abs(t - at) < threshold); if (near !== undefined) { setFeedback(`Snap  /  ${formatWaveTime(near)}`); return near } return at }
 useEffect(() => { if (!ref.current) return; const observer = new ResizeObserver(() => setWidth(ref.current!.clientWidth)); observer.observe(ref.current); return () => observer.disconnect() }, [])
 useEffect(() => { const element = ref.current; if (!element) return; const wheel = (e: WheelEvent) => { if (e.metaKey || e.ctrlKey) { e.preventDefault(); } else if(!e.shiftKey&&Math.abs(e.deltaY)>=Math.abs(e.deltaX))return; else e.preventDefault(); if (e.metaKey || e.ctrlKey) { const anchor = ms(e.clientX), ratio = (e.clientX - element.getBoundingClientRect().left) / width; setView(v => { const spanMs = Math.max(250, Math.min(86400000, v.spanMs * Math.exp(e.deltaY * .003))); return { ...v, spanMs, offsetMs: Math.max(0, anchor - ratio * spanMs) } }) } else { setView(v => ({ ...v, offsetMs: Math.max(0, Math.min(Math.max(0, duration - v.spanMs * .05), v.offsetMs + (e.shiftKey&&Math.abs(e.deltaY)>Math.abs(e.deltaX)?e.deltaY:e.deltaX) / width * v.spanMs)) })) } }; element.addEventListener('wheel', wheel, { passive: false }); return () => element.removeEventListener('wheel', wheel) }, [width, view.offsetMs, view.spanMs, duration])
 function down(e: PointerEvent<HTMLElement>, lane: 'main' | 'sfx' | 'voice', explicit?: string, regionId?: string): void {
   if (e.button !== 0) return
   const at = ms(e.clientX), list = lane === 'sfx' ? sfxRows[Math.max(0, Math.floor((e.clientY-e.currentTarget.getBoundingClientRect().top)/110))] || [] : timeline.clips, c = lane!=='voice'&&regionId?(lane==='sfx'?timeline.sfx:list).find(c=>c.id===regionId):[...list].reverse().find(c => at >= c.startMs && at <= clipEnd(c)), v = lane === 'voice' ? timeline.voices.find(v => regionId ? v.id === regionId : at >= v.startMs && at < v.endMs) : null
   if(c && lane !== 'voice' && (e.shiftKey || e.metaKey || e.ctrlKey)) {
     setView(state=>{const ids=state.selectedIds?.length ? state.selectedIds : state.selectedId ? [state.selectedId] : [];const selected=e.shiftKey ? [...new Set([...ids,c.id])] : ids.includes(c.id) ? ids.filter(id=>id!==c.id) : [...ids,c.id];const clips=list.filter(clip=>selected.includes(clip.id));return {...state, selectedId:c.id, selectedIds:selected, selection:clips.length ? [Math.min(...clips.map(clip=>clip.startMs)),Math.max(...clips.map(clipEnd))] : null}})
     return
   }
   let mode: Drag['mode'] = 'select', id = '', offset = 0
   if (lane === 'voice' && v) { setView(s => ({ ...s, selectedId: v.id, selectedIds:[], selection:null })); id = v.id; if (explicit === 'start') mode = 'voice-start'; else if (explicit === 'end') mode = 'voice-end'; else return }
   else if (explicit === 'selection-start') mode = 'selection-start'
   else if (explicit === 'selection-end') mode = 'selection-end'
   else if (c && lane === 'sfx') { mode = explicit==='start'?'sfx-start':explicit==='end'?'sfx-end':'sfx'; id = c.id; offset = at - c.startMs; setView(s => ({ ...s, selectedId: id, selectedIds:[id],selection:null })) }
   else if(c && lane==='main' && (explicit==='start'||explicit==='end')) {mode=explicit==='start'?'main-start':'main-end';id=c.id;setView(s=>({...s,selectedId:id,selectedIds:[id],selection:null}))}
   else if (c && (e.altKey || (c.sourceId && e.clientY - e.currentTarget.getBoundingClientRect().top < 24))) { mode = 'clip'; id = c.id; offset = at - c.startMs; setView(s => ({ ...s, selectedId: id, selectedIds:[id] })) }
   else if (c && !c.sourceId && Math.abs(x(clipEnd(c)) - (e.clientX - ref.current!.getBoundingClientRect().left)) < 9) { mode = 'silence-resize'; id = c.id }
   else { setView(s => ({ ...s, selectedId: c?.id || null, selectedIds:c ? [c.id] : [], selection: null })); onSeek(Math.min(at, duration)) }
   drag.current = { mode, start: at, pointerX: e.clientX, pointerY: e.clientY, id, original: timeline, offset, moved: false, originView: view }; e.currentTarget.setPointerCapture(e.pointerId)
 }
 function motion(e: PointerEvent<HTMLElement>): void {
   const d = drag.current; if (!d) return
   if (Math.abs(e.clientX - d.pointerX) < 3 && Math.abs(e.clientY-d.pointerY)<3 && !d.moved) return; d.moved = true
   const at = snap(ms(e.clientX), d.id), selectedAt = Math.min(duration, at); setDropAt(null)
   if (d.mode === 'select') setView(v => { const start = Math.min(duration, d.start, selectedAt), end = Math.min(duration, Math.max(d.start, selectedAt)); return { ...v, selection: end > start ? [start, end] : null } })
   else if (d.mode === 'selection-start' || d.mode === 'selection-end') setView(v => { const s = d.originView.selection; if (!s) return v; return { ...v, selection: d.mode === 'selection-start' ? [Math.max(0, Math.min(selectedAt, s[1] - 1)), s[1]] : [s[0], Math.min(duration, Math.max(selectedAt, s[0] + 1))] } })
   else if (d.mode==='sfx-start'||d.mode==='sfx-end'||d.mode==='main-start'||d.mode==='main-end') {const clip=[...d.original.clips,...d.original.sfx].find(c=>c.id===d.id)!;updatePreview(trimSoundtrack(d.original,d.id,d.mode.endsWith('start')?'start':'end',at,sources.find(s=>s.id===clip.sourceId)?.durationMs||clip.sourceEndMs))}
   else if (d.mode === 'clip' && e.clientY >= (ref.current?.querySelector('.wave-sfx-lane')?.getBoundingClientRect().top ?? Infinity)) updatePreview(transferClip(d.original,d.id,'sfx',Math.max(0,at-d.offset)))
   else if (d.mode === 'clip') { const swap = e.shiftKey ? d.original.clips.find(c => c.id !== d.id && at >= c.startMs && at < clipEnd(c)) : undefined; setFeedback(swap ? `Swap with ${swap.name}` : 'Insert / move fragment  /  Shift to swap'); setDropAt(at - d.offset); updatePreview(moveClip(d.original, d.id, snap(Math.max(0, at - d.offset), d.id), swap?.id)) }
   else if (d.mode === 'sfx' && e.clientY >= (ref.current?.querySelector('.wave-main-lane')?.getBoundingClientRect().top ?? Infinity) && e.clientY < (ref.current?.querySelector('.wave-main-lane')?.getBoundingClientRect().bottom ?? 0)) { setFeedback('Move to narration / keep overlap'); updatePreview(transferClip(d.original,d.id,'main',Math.max(0,at-d.offset))) }
   else if (d.mode === 'sfx') updatePreview({ ...d.original, sfx: d.original.sfx.map(c => c.id === d.id ? { ...c, startMs: snap(Math.max(0, at - d.offset), d.id) } : c) })
   else if (d.mode === 'silence-resize') { const c = d.original.clips.find(c => c.id === d.id)!; const end = Math.max(c.startMs + 1, at), delta = end - clipEnd(c); updatePreview({ ...d.original, clips: d.original.clips.map(c2 => c2.id === c.id ? { ...c2, sourceEndMs: c2.sourceStartMs + (end - c2.startMs) * c2.speed } : c2.startMs >= clipEnd(c) ? { ...c2, startMs: c2.startMs + delta } : c2), sfx: d.original.sfx.map(s => s.startMs >= clipEnd(c) ? { ...s, startMs: s.startMs + delta } : s), voices: d.original.voices.map(v => ({ ...v, startMs: v.startMs >= clipEnd(c) ? v.startMs + delta : v.startMs, endMs: v.endMs >= clipEnd(c) ? v.endMs + delta : v.endMs })) }) }
   else updatePreview({ ...d.original, voices: d.original.voices.map(v => v.id === d.id ? d.mode === 'voice-start' ? { ...v, startMs: Math.min(at, v.endMs - 1) } : { ...v, endMs: Math.min(duration, Math.max(at, v.startMs + 1)) } : v) })
 }
 function finish(e: PointerEvent<HTMLElement>): void { if(drag.current?.mode==='sfx'&&!drag.current.moved)onSeek(Math.min(duration,drag.current.start));if (drag.current?.moved && previewRef.current) edit(previewRef.current); drag.current = null; updatePreview(null); setFeedback(''); setDropAt(null); if (e.currentTarget.hasPointerCapture(e.pointerId)) e.currentTarget.releasePointerCapture(e.pointerId) }
 const step = [100, 250, 500, 1000, 2000, 5000, 10000, 30000, 60000, 300000, 600000, 1800000, 3600000].find(n => n / view.spanMs * width > 80) || 3600000
 const ticks = Array.from({ length: Math.ceil(view.spanMs / step) + 1 }, (_, i) => Math.ceil(view.offsetMs / step) * step + i * step)
 const laneHandlers = (lane: 'main' | 'sfx' | 'voice') => ({ onPointerDown: (e: PointerEvent<HTMLElement>) => down(e, lane), onPointerMove: motion, onPointerUp: finish, onPointerCancel: () => { drag.current = null; updatePreview(null); setFeedback('') } })
 return <section className="wave-timeline-wrap"><div className="wave-lane-titles">{!!videos.length&&<span style={{height:44}}>Video</span>}<span>Voices</span><span>Narration</span><span>Soundtracks / effects</span></div><div className="wave-timeline" ref={ref}>
   <div className="wave-ruler" onPointerDown={e => onSeek(Math.min(duration, ms(e.clientX)))}>{ticks.map(t => <span key={t} style={{ left: x(t) }}>{formatWaveTime(t)}</span>)}</div>
   {!!videos.length&&<div className="wave-video-lane">{shownVideos.map(v=><div key={v.id} className={`wave-video-clip ${view.selectedId===v.id?'selected':''}`} style={{left:x(v.startMs),width:Math.max(12,x(v.startMs+v.durationMs)-x(v.startMs))}} onPointerDown={e=>videoDown(e,v)} onPointerMove={videoMotion} onPointerUp={videoFinish} onPointerCancel={e=>videoFinish(e,true)}>{(['start','end'] as const).map(edge=><button key={edge} className={`wave-sfx-handle ${edge}`} aria-label={`Video ${edge} / ${v.name}`} onPointerDown={e=>videoDown(e,v,edge)} />)}Video {v.name} / muted</div>)}{videoHolds(shownVideos,duration).map(h=><div key={`hold-${h.video.id}`} className="wave-video-hold" role="img" aria-label={`Held final frame / ${h.video.name} / ${formatWaveTime(h.startMs)} to ${formatWaveTime(h.endMs)}`} style={{left:x(h.startMs),width:Math.max(0,x(h.endMs)-x(h.startMs))}}>Hold final frame</div>)}</div>}
   <div className="wave-voice-lane" {...laneHandlers('voice')}>{shown.voices.filter(v => v.startMs < view.offsetMs + view.spanMs && v.endMs > view.offsetMs).slice(0, 200).map(v => <div key={v.id} className={`wave-voice-region ${v.production?.status || 'assigned'} ${view.selectedId === v.id ? 'selected' : ''}`} style={{ left: x(v.startMs), width: Math.max(2, x(v.endMs) - x(v.startMs)), backgroundColor: v.color }}><span className="wave-edge" onPointerDown={e => { e.stopPropagation(); down(e, 'voice', 'start', v.id) }} /><span>{v.name}  /  <small>{v.production?.status || 'assigned'}</small></span><span className="wave-edge end" onPointerDown={e => { e.stopPropagation(); down(e, 'voice', 'end', v.id) }} /></div>)}</div>
   <div className="wave-main-lane" onDoubleClick={e=>{const at=ms(e.clientX),clip=timeline.clips.find(c=>at>=c.startMs && at<clipEnd(c));if(clip)setView(v=>({...v,selectedId:clip.id,selectedIds:[clip.id],selection:[clip.startMs,clipEnd(clip)]}))}} onDragOver={e=>{e.preventDefault();setDropAt(ms(e.clientX))}} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('application/homer-sfx');if(id)onSfxDrop(id,ms(e.clientX),'main');setDropAt(null)}} {...laneHandlers('main')}>{shown.voices.map(v=><div key={v.id} className="wave-voice-tint" style={{left:x(v.startMs),width:x(v.endMs)-x(v.startMs),background:v.color,color:v.color}}/>)}<WaveformCanvas clips={shown.clips} view={view} height={280} selectedId={view.selectedId} onError={onError} />{shown.clips.filter(c=>c.id===view.selectedId&&c.sourceId).map(c=><div key={c.id} className="wave-sfx-trim wave-main-trim" style={{left:x(c.startMs),width:Math.max(12,x(clipEnd(c))-x(c.startMs))}}>{(['start','end'] as const).map(edge=><button key={edge} className={`wave-sfx-handle ${edge}`} aria-label={`Narration ${edge}`} onPointerDown={e=>{e.stopPropagation();down(e,'main',edge,c.id)}} />)}</div>)}{view.selection && <div className="wave-selection" style={{ left: x(view.selection[0]), width: x(view.selection[1]) - x(view.selection[0]) }}><button aria-label="Selection start" onPointerDown={e => { e.stopPropagation(); down(e as unknown as PointerEvent<HTMLElement>, 'main', 'selection-start') }} /><button aria-label="Selection end" onPointerDown={e => { e.stopPropagation(); down(e as unknown as PointerEvent<HTMLElement>, 'main', 'selection-end') }} /></div>}</div>
   <div className="wave-sfx-lane" style={{height:sfxRows.length*110}} {...laneHandlers('sfx')} onDragOver={e => { e.preventDefault(); setDropAt(snap(ms(e.clientX))); setFeedback(`Place sound effect  /  ${formatWaveTime(ms(e.clientX))}`) }} onDragLeave={() => { setDropAt(null); setFeedback('') }} onDrop={e => { e.preventDefault(); const id = e.dataTransfer.getData('application/homer-sfx'); if (id) onSfxDrop(id, snap(ms(e.clientX))); setDropAt(null); setFeedback('') }}>{sfxRows.map((row,i)=><div key={i} style={{height:110,position:"relative"}}><WaveformCanvas clips={row} view={view} height={110} selectedId={view.selectedId} onError={onError} />{row.filter(c=>c.id===view.selectedId).map(c=><div key={c.id} className="wave-sfx-trim" style={{left:x(c.startMs),width:Math.max(12,x(clipEnd(c))-x(c.startMs))}}>{(['start','end'] as const).map(edge=><button key={edge} className={`wave-sfx-handle ${edge}`} aria-label={`Soundtrack ${edge}`} onPointerDown={e=>{e.stopPropagation();down(e,'sfx',edge,c.id)}} onKeyDown={e=>{if(e.key!=='ArrowLeft'&&e.key!=='ArrowRight')return;e.preventDefault();e.stopPropagation();const at=(edge==='start'?c.startMs:clipEnd(c))+(e.key==='ArrowRight'?1:-1)*(e.shiftKey?100:10);edit(trimSoundtrack(timeline,c.id,edge,at,sources.find(s=>s.id===c.sourceId)?.durationMs||c.sourceEndMs))}}/> )}</div>)}</div>)}{!shown.sfx.length && <span className="wave-sfx-placeholder">Drop audio here to add a separate soundtrack</span>}</div>
   <div className="wave-playhead" style={{ left: x(view.playheadMs) }} /><div className="wave-drop-line" style={{ display: dropAt === null ? 'none' : 'block', left: x(dropAt || 0) }} />
 </div><footer><span>{view.selection ? `${formatWaveTime(view.selection[0])}  -  ${formatWaveTime(view.selection[1])}  /  ${((view.selection[1] - view.selection[0]) / 1000).toFixed(3)}s selected` : 'Drag to select  /  Option-drag to move a fragment  /  Shift while moving to swap'}</span><span role="status">{feedback}</span></footer><label className="wave-zoom">Zoom<StudioSlider aria-label="Timeline zoom" min={0} max={100} step={1} value={Math.max(0,Math.min(100,100*(1-Math.log(Math.max(250,view.spanMs)/250)/Math.log(Math.max(500,duration*1.025)/250))))} onChange={e=>setView(v=>{const spanMs=250*Math.pow(Math.max(500,duration*1.025)/250,1-Number(e.target.value)/100),ratio=Math.max(0,Math.min(1,(v.playheadMs-v.offsetMs)/v.spanMs));return {...v,spanMs,offsetMs:Math.max(0,v.playheadMs-ratio*spanMs)}})} /></label><label className="wave-zoom">View<StudioSlider aria-label="Timeline view" min={0} max={Math.max(0,duration-view.spanMs*.9)} step={10} value={view.offsetMs} onChange={e=>setView(v=>({...v,offsetMs:Number(e.target.value)}))}/></label></section>
}
