import { useEffect, useState } from 'react'
import type { Voice } from '../../../shared/contracts'
import { clipDuration, clipEnd, formatWaveTime, timelineDuration, sourceClip, speedPresets, type WaveClip } from '../../../shared/waveStudio'
import { assignVoice, changeSpeed, insertSilence, removeRange } from '../../../shared/waveStudioEdits'
import { useWaveStudio } from '../WaveStudioProvider'
function NumberField({ label, value, min = 0, max = 86400000, step = 1, commit }: { label: string; value: number; min?: number; max?: number; step?: number; commit: (n: number) => void }): JSX.Element {
 return <label>{label}<input type="number" key={`${label}:${value}`} defaultValue={Number(value.toFixed(3))} min={min} max={max} step={step} onBlur={e => { const n = Number(e.target.value); if (e.target.value !== '' && Number.isFinite(n) && n >= min && n <= max && n !== value) commit(n); else e.target.value = String(value) }} onKeyDown={e => { if (e.key === 'Enter') e.currentTarget.blur() }} /></label>
}
export function WaveStudioInspector({ voices, onManageVoices }: { voices: Voice[]; onManageVoices: () => void }): JSX.Element {
 const w = useWaveStudio(), t = w.project?.timeline, clip = t?.clips.find(c => c.id === w.view.selectedId), sfx = t?.sfx.find(c => c.id === w.view.selectedId), region = t?.voices.find(v => v.id === w.view.selectedId)
 const [speed, setSpeed] = useState(1)
 useEffect(() => { setSpeed((clip || sfx)?.speed || 1) }, [clip?.id, clip?.speed, sfx?.id, sfx?.speed])
 const c = clip ?? sfx
 function update(patch: Partial<WaveClip>): void { if (!t || !c) return; w.edit({ ...t, [sfx ? 'sfx' : 'clips']: (sfx ? t.sfx : t.clips).map(x => x.id === c.id ? { ...x, ...patch } : x) }) }
 function silenceDuration(n: number): void { if (!t || !clip) return; const at = clip.startMs; const removed = removeRange(t, at, clipEnd(clip)); w.edit(insertSilence(removed, at, n)) }
 return <aside className="wave-inspector"><h2>{region ? 'Voice region' : sfx ? 'Sound effect' : clip ? clip.sourceId ? 'Audio fragment' : 'Silence' : 'Selection'}</h2>
 {region && t ? <><strong style={{ color: region.color }}>{region.name}</strong><NumberField label="Start (ms)" value={region.startMs} max={region.endMs - 1} commit={n => w.edit({ ...t, voices: t.voices.map(v => v.id === region.id ? { ...v, startMs: n } : v) })} /><NumberField label="End (ms)" value={region.endMs} min={region.startMs + 1} max={timelineDuration(t)} commit={n => w.edit({ ...t, voices: t.voices.map(v => v.id === region.id ? { ...v, endMs: n } : v) })} /><label>Assigned voice<select value={region.voiceId} onChange={e => { const v = voices.find(v => v.id === e.target.value); if (v) w.edit(assignVoice({ ...t, voices: t.voices.filter(v => v.id !== region.id) }, region.startMs, region.endMs, v)) }}>{!voices.some(v => v.id === region.voiceId) && <option value={region.voiceId}>{region.name} (removed from library)</option>}{voices.map(v => <option value={v.id} key={v.id}>{v.name}</option>)}</select></label><button onClick={onManageVoices}>Open voice library</button><button onClick={() => w.edit({ ...t, voices: t.voices.filter(v => v.id !== region.id) })}>Remove region</button><p>Voice labels mark the passage. Use Voice Lab to convert its audio.</p></> : c && t ? <><strong>{c.name}</strong><dl><div><dt>Start</dt><dd>{formatWaveTime(c.startMs)}</dd></div><div><dt>End</dt><dd>{formatWaveTime(clipEnd(c))}</dd></div><div><dt>Duration</dt><dd>{formatWaveTime(clipDuration(c))}</dd></div></dl>
 {!c.sourceId ? <NumberField label="Silence duration (ms)" value={clipDuration(c)} min={1} commit={silenceDuration} /> : <>
 {sfx && <><NumberField label="Start (ms)" value={c.startMs} commit={n => update({ startMs: n })} /><NumberField label="Source in (ms)" value={c.sourceStartMs} max={c.sourceEndMs - 1} commit={n => update({ sourceStartMs: n, fadeInMs: Math.min(c.fadeInMs, (c.sourceEndMs - n) / c.speed), fadeOutMs: Math.min(c.fadeOutMs, (c.sourceEndMs - n) / c.speed) })} /><NumberField label="Source out (ms)" value={c.sourceEndMs} min={c.sourceStartMs + 1} max={w.project?.sources.find(s => s.id === c.sourceId)?.durationMs || c.sourceEndMs} commit={n => update({ sourceEndMs: n, fadeInMs: Math.min(c.fadeInMs, (n - c.sourceStartMs) / c.speed), fadeOutMs: Math.min(c.fadeOutMs, (n - c.sourceStartMs) / c.speed) })} /></>}
 <NumberField label="Gain (dB)" value={c.gainDb} min={-96} max={6} step={.5} commit={n => update({ gainDb: n })} /><div className="wave-presets">{[-30, -20, -10, 0].map(db => <button key={db} onClick={() => update({ gainDb: db })}>{db} dB</button>)}<button onClick={() => update({ gainDb: c.gainDb <= -96 ? -10 : -96 })}>{c.gainDb <= -96 ? 'Unmute' : 'Mute (−∞)'}</button></div>
 <NumberField label="Fade in (ms)" value={c.fadeInMs} max={clipDuration(c)} commit={n => update({ fadeInMs: n })} /><NumberField label="Fade out (ms)" value={c.fadeOutMs} max={clipDuration(c)} commit={n => update({ fadeOutMs: n })} />
 {clip && <><label>Speed · {c.speed.toFixed(2)}×<input type="range" min={.85} max={1.2} step={.01} defaultValue={c.speed} key={c.speed} onChange={e => setSpeed(Number(e.target.value))} onPointerUp={e => w.edit(changeSpeed(t, c.startMs, clipEnd(c), Number(e.currentTarget.value)))} onKeyUp={e => w.edit(changeSpeed(t, c.startMs, clipEnd(c), Number(e.currentTarget.value)))} /></label><NumberField label="Playback speed" value={c.speed} min={.85} max={1.2} step={.01} commit={n => w.edit(changeSpeed(t, c.startMs, clipEnd(c), n))} /><div className="wave-presets">{speedPresets.map(n => <button key={n} onClick={() => w.edit(changeSpeed(t, c.startMs, clipEnd(c), n))}>{n.toFixed(2)}×</button>)}</div><p>Pitch preserved. Original {formatWaveTime(c.sourceEndMs - c.sourceStartMs)} → {formatWaveTime((c.sourceEndMs - c.sourceStartMs) / (speed || c.speed))}</p><label>Voice<select defaultValue="" onChange={e => { const v = voices.find(v => v.id === e.target.value); if (v) w.edit(assignVoice(t, c.startMs, clipEnd(c), v)) }}><option value="">Assign to fragment…</option>{voices.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label></>}
 </>}
 {sfx ? <><button onClick={() => { const clone = { ...c, id: crypto.randomUUID(), startMs: clipEnd(c) }; w.edit({ ...t, sfx: [...t.sfx, clone] }) }}>Duplicate</button><button onClick={() => w.edit({ ...t, sfx: t.sfx.filter(x => x.id !== c.id) })}>Delete sound effect</button></> : <button onClick={() => { w.edit(removeRange(t, c.startMs, clipEnd(c))); w.setView(v => ({ ...v, selectedId: null })) }}>Delete fragment & close gap</button>}
 </> : <><p>{w.view.selection ? `${formatWaveTime(w.view.selection[0])} → ${formatWaveTime(w.view.selection[1])}` : 'Select a fragment, voice region or sound effect to adjust it.'}</p><p>Drag across the waveform to select a passage. Drag a fragment’s title to move it.</p></>}
 </aside>
}
