import { StudioSlider } from './StudioControls'
import { NeutralSlider } from './NeutralSlider'
import { useEffect, useState, useRef } from 'react'
import type { Voice } from '../../../shared/contracts'
import { clipDuration, clipEnd, formatWaveTime, timelineDuration, sourceClip, type WaveClip } from '../../../shared/waveStudio'
import { assignVoice, changeSpeed, insertSilence, removeRange, soundtrackRange } from '../../../shared/waveStudioEdits'
import { waveApi } from '../waveStudioNative'
import { errorMessage } from '../native'
import { useWaveStudio } from '../WaveStudioProvider'
function NumberField({ label, value, min = 0, max = 86400000, step = 1, commit }: { label: string; value: number; min?: number; max?: number; step?: number; commit: (n: number) => void }): JSX.Element {
 return <label>{label}<input type="number" key={`${label}:${value}`} defaultValue={Number(value.toFixed(3))} min={min} max={max} step={step} onBlur={e => { const n = Number(e.target.value); if (e.target.value !== '' && Number.isFinite(n) && n >= min && n <= max && n !== value) commit(n); else e.target.value = String(value) }} onKeyDown={e => { if (e.key === 'Enter') e.currentTarget.blur() }} /></label>
}
export function WaveStudioInspector({ voices, onManageVoices, onGenerateVoice, onListenVoice }: { voices: Voice[]; onManageVoices: () => void; onGenerateVoice: (id:string)=>void; onListenVoice:(id:string)=>void }): JSX.Element {
 const w = useWaveStudio(), t = w.project?.timeline, clip = t?.clips.find(c => c.id === w.view.selectedId), sfx = t?.sfx.find(c => c.id === w.view.selectedId), region = t?.voices.find(v => v.id === w.view.selectedId)
 const [speed, setSpeed] = useState(1)
 useEffect(() => { setSpeed((clip || sfx)?.speed || 1) }, [clip?.id, clip?.speed, sfx?.id, sfx?.speed])
 const latest=useRef(w.project);latest.current=w.project
 const [normalizing,setNormalizing]=useState(false),[normalizeInfo,setNormalizeInfo]=useState('')
 const c = clip ?? sfx
 function update(patch: Partial<WaveClip>): void { if (!t || !c) return; w.edit({ ...t, [sfx ? 'sfx' : 'clips']: (sfx ? t.sfx : t.clips).map(x => x.id === c.id ? { ...x, ...patch } : x) }) }
 function sourceRange(sourceIn:number,sourceOut:number):void{if(!c)return;update(soundtrackRange(c,sourceIn,sourceOut,w.project?.sources.find(s=>s.id===c.sourceId)?.durationMs||c.sourceEndMs))}
 function silenceDuration(n: number): void { if (!t || !clip) return; const at = clip.startMs; const removed = removeRange(t, at, clipEnd(clip)); w.edit(insertSilence(removed, at, n)) }
 return <aside className="wave-inspector"><h2>{region ? 'Voice region' : sfx ? 'Soundtrack fragment' : clip ? clip.sourceId ? 'Audio fragment' : 'Silence' : 'Selection'}</h2>
 {region && t ? <><strong style={{ color: region.color }}>{region.name}</strong><NumberField label="Start (ms)" value={region.startMs} max={region.endMs - 1} commit={n => w.edit({ ...t, voices: t.voices.map(v => v.id === region.id ? { ...v, startMs: n } : v) })} /><NumberField label="End (ms)" value={region.endMs} min={region.startMs + 1} max={timelineDuration(t)} commit={n => w.edit({ ...t, voices: t.voices.map(v => v.id === region.id ? { ...v, endMs: n } : v) })} /><label>Assigned voice<select value={region.voiceId} onChange={e => { const v = voices.find(v => v.id === e.target.value); if (v) w.edit(assignVoice({ ...t, voices: t.voices.filter(v => v.id !== region.id) }, region.startMs, region.endMs, v)) }}>{!voices.some(v => v.id === region.voiceId) && <option value={region.voiceId}>{region.name} (removed from library)</option>}{voices.map(v => <option value={v.id} key={v.id}>{v.name}</option>)}</select></label><span className="wave-voice-badge">{region.production?.status || 'assigned'}</span><button className="primary" onClick={()=>onGenerateVoice(region.id)}>{region.production?'Regenerate / preview voice':'Generate / preview voice'}</button><button onClick={()=>onListenVoice(region.id)}>Listen to passage</button><button onClick={onManageVoices}>Open voice library</button><button onClick={() => w.edit({ ...t, voices: t.voices.filter(v => v.id !== region.id) })}>Remove region</button><p>Voice labels mark the passage. Use Apply tagged voices in the top toolbar to convert, preview and accept this audio.</p></> : c && t ? <><strong>{c.name}</strong><dl><div><dt>Start</dt><dd>{formatWaveTime(c.startMs)}</dd></div><div><dt>End</dt><dd>{formatWaveTime(clipEnd(c))}</dd></div><div><dt>Duration</dt><dd>{formatWaveTime(clipDuration(c))}</dd></div></dl>
 {!c.sourceId ? <NumberField label="Silence duration (ms)" value={clipDuration(c)} min={1} commit={silenceDuration} /> : <>
 {sfx && <><NumberField label="Start (ms)" value={c.startMs} commit={n => update({ startMs: n })} /><NumberField label="Source in (ms)" value={c.sourceStartMs} max={c.sourceEndMs - 1} commit={n => sourceRange(n,c.sourceEndMs)} /><NumberField label="Source out (ms)" value={c.sourceEndMs} min={c.sourceStartMs + 1} max={w.project?.sources.find(s => s.id === c.sourceId)?.durationMs || c.sourceEndMs} commit={n => sourceRange(c.sourceStartMs,n)} /></>}
 <label>Level  /  {c.gainDb.toFixed(1)} dB<NeutralSlider label="Fragment level" min={-96} max={20} step={.5} value={c.gainDb} onChange={gainDb=>update({gainDb})} /></label><button disabled={normalizing || !c.sourceId} onClick={()=>{const project=w.project!, selected=c.id, before=JSON.stringify(t);setNormalizing(true);void waveApi.normalize(project,selected).then(gain=>{if(project.id!==latest.current?.id || JSON.stringify(latest.current.timeline)!==before)throw new Error('Timeline changed during measurement. Normalize this fragment again.');update({gainDb:gain});setNormalizeInfo(`${gain>=0?'+':''}${gain.toFixed(1)} dB applied. ${gain<0?'The peak exceeded -1 dB, so normalization reduced the level.':gain===20?'Boost limited to +20 dB.':'Peak target: -1 dB.'}`)}).catch(e=>w.setError(errorMessage(e))).finally(()=>setNormalizing(false))}}>{normalizing?'Measuring...':'Normalize'}</button>{normalizeInfo&&<p role="status">{normalizeInfo}</p>}<div className="wave-presets">{[-20, -10, 0, 10, 20].map(db => <button key={db} onClick={() => update({ gainDb: db })}>{db>0?'+':''}{db} dB</button>)}<button onClick={() => update({ gainDb: c.gainDb <= -96 ? -10 : -96 })}>{c.gainDb <= -96 ? 'Unmute' : 'Mute'}</button></div>
 <label>Fade in  /  {(c.fadeInMs/1000).toFixed(2)}s<StudioSlider aria-label="Fade in" min={0} max={clipDuration(c)} step={10} value={c.fadeInMs} onChange={e=>update({fadeInMs:Number(e.target.value)<Math.min(50,clipDuration(c)*.02)?0:Number(e.target.value)})} /></label><label>Fade out  /  {(c.fadeOutMs/1000).toFixed(2)}s<StudioSlider aria-label="Fade out" min={0} max={clipDuration(c)} step={10} value={c.fadeOutMs} onChange={e=>update({fadeOutMs:Number(e.target.value)<Math.min(50,clipDuration(c)*.02)?0:Number(e.target.value)})} /></label>
 {clip && <><label>Speed  /  {((speed-1)*100).toFixed(0)}%  /  {speed.toFixed(2)}x<NeutralSlider label="Fragment speed" min={.85} max={1.2} neutral={1} step={.01} value={speed} onChange={n=>{setSpeed(n);w.edit(changeSpeed(t,c.startMs,clipEnd(c),n))}} /></label><p>Pitch preserved. Original {formatWaveTime(c.sourceEndMs - c.sourceStartMs)} to {formatWaveTime((c.sourceEndMs - c.sourceStartMs) / (speed || c.speed))}</p><label>Voice<select defaultValue="" onChange={e => { const v = voices.find(v => v.id === e.target.value); if (v) w.edit(assignVoice(t, c.startMs, clipEnd(c), v)) }}><option value="">Assign to fragment...</option>{voices.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label></>}
 </>}
 {sfx ? <><button onClick={() => { const clone = { ...c, id: crypto.randomUUID(), startMs: clipEnd(c) }; w.edit({ ...t, sfx: [...t.sfx, clone] }) }}>Duplicate</button><button onClick={() => w.edit({ ...t, sfx: t.sfx.filter(x => x.id !== c.id) })}>Delete soundtrack fragment</button></> : <button onClick={() => { w.edit(removeRange(t, c.startMs, clipEnd(c))); w.setView(v => ({ ...v, selectedId: null })) }}>Delete fragment & close gap</button>}
 </> : <><p>{w.view.selection ? `${formatWaveTime(w.view.selection[0])} to ${formatWaveTime(w.view.selection[1])}` : 'Select a fragment, voice region or sound effect to adjust it.'}</p><p>Drag across the waveform to select a passage. Drag a fragment's title to move it.</p></>}
 </aside>
}
