import { useEffect, useRef, useState } from 'react'
import type { WaveVideo, WaveView } from '../../../shared/waveStudio'
import { formatWaveTime, videoFrame, placeVideo } from '../../../shared/waveStudio'
import { waveApi } from '../waveStudioNative'
import { open } from '../platform'
import { errorMessage } from '../native'
export function WaveVideoReference({videos,view,playing,setVideos,setView,onError}:{videos:WaveVideo[];view:WaveView;playing:boolean;setVideos:(v:WaveVideo[])=>void;setView:React.Dispatch<React.SetStateAction<WaveView>>;onError:(m:string)=>void}):JSX.Element {
 const frame=videoFrame(videos,view.playheadMs)
 const active=videos.find(v=>v.id===view.selectedId)||videos.find(v=>view.playheadMs>=v.startMs&&view.playheadMs<v.startMs+v.durationMs)||videos[0], ref=useRef<HTMLVideoElement>(null),[url,setUrl]=useState(''),[missing,setMissing]=useState(false),[locating,setLocating]=useState(false)
 useEffect(()=>{let alive=true;setUrl('');setMissing(false);if(frame)void waveApi.videoUrl(frame.video.id).then(u=>{if(alive)setUrl(u)}).catch(()=>{if(alive)setMissing(true)});return()=>{alive=false}},[frame?.video.id])
 function sync():void{const video=ref.current;if(!video||!frame)return;video.muted=true;const time=frame.timeMs/1000;if(Math.abs(video.currentTime-time)>.15||!playing||frame.held)video.currentTime=time;const inside=!frame.held;if(playing&&inside){if(video.paused)void video.play().catch(()=>{})}else video.pause()}
 useEffect(sync,[view.playheadMs,playing,frame?.video.id,url,frame?.video.startMs])
 if(!active)return <></>
 return <section className="wave-video-reference"><span className="wave-video-screen"><video style={{visibility:frame?'visible':'hidden'}} ref={ref} src={url||undefined} muted playsInline preload="metadata" onLoadedMetadata={sync} onError={()=>{if(!url)return;setMissing(true);onError('This video reference could not be displayed. Locate its source file.')}} /></span><div><small>VIDEO REFERENCE  /  MUTED</small><label className="wave-video-choice">Selected video<select aria-label="Selected video" value={active.id} onChange={e=>setView(v=>({...v,selectedId:e.target.value,selectedIds:[],selection:null}))}>{videos.map((video,i)=><option key={video.id} value={video.id}>{i+1}. {video.name}</option>)}</select></label><p className="wave-video-frame-time">{frame?.held?'Holding final frame':'Current frame'}  /  {formatWaveTime(frame?.timeMs||0)}</p><label className="wave-video-start">Timeline start (seconds)<input key={`${active.id}:${active.startMs}`} type="number" min={0} max={(86400000-active.durationMs)/1000} step={.001} defaultValue={active.startMs/1000} onBlur={e=>{try{const n=Number(e.target.value)*1000;if(Number.isFinite(n)&&n>=0&&n+active.durationMs<=86400000)setVideos(videos.map(v=>v.id===active.id?{...v,startMs:placeVideo(videos,active.durationMs,n,active.id)}:v))}catch(e){onError(errorMessage(e))}}}/></label>{missing&&<p>Linked video is unavailable. Locate the source file to restore it.</p>}<div className="wave-video-actions"><button disabled={locating} onClick={()=>void (async()=>{setLocating(true);try{const path=await open({title:'Locate video',multiple:false});if(typeof path==='string'){const next=await waveApi.importVideo(path);setVideos(videos.map(v=>v.id===active.id?{...next,startMs:placeVideo(videos,next.durationMs,v.startMs,active.id)}:v));setView(v=>({...v,selectedId:v.selectedId===active.id?next.id:v.selectedId}));}}catch(e){onError(errorMessage(e))}finally{setLocating(false)}})()}>{missing?'Locate video':'Relink video'}</button><button onClick={()=>setView(v=>({...v,playheadMs:active.startMs,selectedId:active.id}))}>Go to video start</button><button onClick={()=>{ref.current?.pause();setVideos(videos.filter(v=>v.id!==active.id));setView(v=>({...v,selectedId:null,selectedIds:[],selection:null}))}}>Remove selected video</button></div></div></section>
}
