import { Checkbox } from './StudioControls'
import { formatWaveTime, projectDuration } from '../../../shared/waveStudio'
import { useWaveStudio } from '../WaveStudioProvider'
interface Props { playing: boolean; loading: boolean; play: (selection?: boolean) => void; seek: (ms: number) => void; fit: (selection?: boolean) => void; zoom: (factor: number) => void; onImport: () => void; onExport: () => void; onProjects: () => void; onRecord?: () => void; onSpeech?: () => void; onJoin?: () => void; onVoices?: () => void }
export function WaveStudioToolbar({ playing, loading, play, seek, fit, zoom, onImport, onExport, onProjects, onRecord, onSpeech, onJoin, onVoices }: Props): JSX.Element {
 const w = useWaveStudio(), duration = w.project ? projectDuration(w.project) : 0
 return <header className="wave-toolbar"><div className="wave-project-title"><span>Wave Studio</span><input aria-label="Wave project name" key={w.project?.id} defaultValue={w.project?.name || 'Untitled narration'} maxLength={80} disabled={!w.project} onBlur={e => { const name = e.target.value.trim(); if (name && name !== w.project?.name) w.rename(name) }} /><small role="status">{w.operation ? `${w.operation.label}  /  ${w.operation.progress}%` : w.busy ? 'Working...' : w.saveStatus}</small>{w.operation&&<button onClick={w.cancelOperation}>Cancel import</button>}</div>
 <div className="wave-toolbar-group"><button title="Undo (Command+Z)" aria-label="Undo" disabled={!w.history.past.length} onClick={w.undo}>Undo</button><button title="Redo (Shift+Command+Z)" aria-label="Redo" disabled={!w.history.future.length} onClick={w.redo}>Redo</button></div>
 <div className="wave-toolbar-group"><button title="Back 5 seconds" onClick={() => seek(Math.max(0, w.view.playheadMs - 5000))}>-5s</button><button className="wave-play" disabled={!duration || w.busy} title="Play / pause (Space)" onClick={() => play()}>{loading ? 'Loading...' : playing ? 'Pause' : 'Play'}</button><button title="Forward 5 seconds" onClick={() => seek(Math.min(duration, w.view.playheadMs + 5000))}>+5s</button><label className="wave-loop"><Checkbox checked={w.view.loop} onChange={e => w.setView(v=>({...v,loop:e.target.checked}))} />Loop</label><span className="wave-time">{formatWaveTime(w.view.playheadMs)} <small>/ {formatWaveTime(duration)}</small></span></div>
 <div className="wave-toolbar-group"><button title="Zoom out (-)" onClick={() => zoom(1.5)}>-</button><button title="Zoom in (+)" onClick={() => zoom(1 / 1.5)}>+</button><button title="Fit project (0)" onClick={() => fit()}>Fit</button><button disabled={!w.view.selection} onClick={() => fit(true)}>Fit selection</button></div>
 <div className="wave-toolbar-group wave-toolbar-end"><button disabled={w.busy} onClick={onProjects}>Projects</button><button disabled={w.busy} onClick={onImport}>Import</button><button disabled={!duration || w.busy} onClick={onExport}>Export</button></div><div className="wave-toolbar-group"><button disabled={w.busy} onClick={onRecord}> Record</button><button disabled={w.busy} onClick={onSpeech}>Generate speech</button><button disabled={!duration || w.busy} onClick={onJoin}>Join</button><button disabled={!w.project?.timeline.voices.length || w.busy} onClick={onVoices}>Apply tagged voices</button></div></header>
}
