import { useEffect, useState } from 'react'
import { clipEnd, formatWaveTime, sfxCategories, type SfxAsset } from '../../../shared/waveStudio'
import { AudioTransport } from './AudioTransport'
import { chooseAudio, errorMessage, isDesktop, soundsApi } from '../native'
import type { SoundAsset } from '../../../shared/contracts'
import { waveApi } from '../waveStudioNative'
import { useWaveStudio } from '../WaveStudioProvider'
interface Props { full?: boolean; onClose: () => void; onManage?: () => void; onAdded?: () => void }
export function WaveStudioLibraryDrawer({ full = false, onClose, onManage, onAdded }: Props): JSX.Element {
 const w = useWaveStudio(), [assets, setAssets] = useState<SfxAsset[]>([]), [legacy, setLegacy] = useState<SoundAsset[]>([]), [query, setQuery] = useState(''), [category, setCategory] = useState('All'), [align, setAlign] = useState('end'), [url, setUrl] = useState(''), [previewId, setPreviewId] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false), [editing, setEditing] = useState<SfxAsset | null>(null)
 const [recent, setRecent] = useState<string[]>(() => { try { return JSON.parse(localStorage.getItem('homer.sfx.recent') || '[]') as string[] } catch { return [] } })
 async function refresh(): Promise<void> { if (isDesktop()) { const [found, clips] = await Promise.all([waveApi.sfx(), soundsApi.list()]); setAssets(found); setLegacy(clips) } }
 useEffect(() => { void refresh().catch(e => setError(errorMessage(e))) }, [])
 async function task(fn: () => Promise<void>): Promise<void> { setBusy(true); setError(''); try { await fn() } catch (e) { setError(errorMessage(e)) } finally { setBusy(false) } }
 function add(a: SfxAsset): void {
   if (!w.project) { setError('Open or import narration in Wave Studio first.'); return }
   let at = w.view.selection ? align === 'start' ? w.view.selection[0] : align === 'center' ? (w.view.selection[0] + w.view.selection[1]) / 2 : w.view.selection[1] : w.view.playheadMs
   if (a.category === 'Transitions') { const boundary = w.project.timeline.clips.flatMap(c => [c.startMs, clipEnd(c)]).sort((a, b) => Math.abs(a - at) - Math.abs(b - at))[0]; if (boundary !== undefined && Math.abs(boundary - at) < 500) at = boundary }
   w.addSource(a, at); const next = [a.id, ...recent.filter(id => id !== a.id)].slice(0, 12); setRecent(next); localStorage.setItem('homer.sfx.recent', JSON.stringify(next)); onAdded?.()
 }
 const filtered = assets.filter(a => (!query || a.name.toLowerCase().includes(query.toLowerCase())) && (category === 'All' || category === 'Recent' ? category !== 'Recent' || recent.includes(a.id) : a.category === category))
 return <section className={full ? 'wave-sfx-library full' : 'wave-sfx-library'}><header><div><h2>{full ? 'SFX library' : 'Add a sound effect'}</h2><p>Local sounds · narration remains intact</p></div><div className="wave-toolbar-group">{onManage && <button onClick={onManage}>Manage SFX</button>}<button onClick={onClose}>{full ? '← Back to Wave Studio' : 'Close'}</button></div></header>
 {error && <div className="inline-error" role="alert">{error}</div>}
 <div className="wave-library-tools"><input aria-label="Search sound effects" placeholder="Search sounds…" value={query} onChange={e => setQuery(e.target.value)} /><select aria-label="Sound category" value={category} onChange={e => setCategory(e.target.value)}>{['All', 'Recent', ...sfxCategories].map(c => <option key={c}>{c}</option>)}</select><select aria-label="Sound alignment" value={align} onChange={e => setAlign(e.target.value)}><option value="start">Selection start</option><option value="center">Selection center</option><option value="end">Selection end / punchline</option></select><button disabled={busy || !isDesktop()} onClick={() => void task(async () => { const path = await chooseAudio(); if (path) setAssets(await waveApi.addSfx(await waveApi.import('file', path), sfxCategories.includes(category as typeof sfxCategories[number]) ? category : 'Custom')) })}>Import custom sound</button></div>
 {!filtered.length && <p className="wave-empty-library">{isDesktop() ? 'No sounds in this category yet. Import your own audio.' : 'Open Homer Studio on your Mac to browse local sounds.'}</p>}
 <div className="wave-sfx-rows">{filtered.map(a => <article key={a.id} draggable onDragStart={e => { e.dataTransfer.setData('application/homer-sfx', a.id); e.dataTransfer.effectAllowed = 'copy' }}><div className="wave-sfx-icon">♪</div><div><strong>{a.name}</strong><small>{a.category} · {formatWaveTime(a.durationMs)}{a.builtIn ? ' · bundled' : ''}</small></div><button aria-label={`Preview ${a.name}`} disabled={busy} onClick={() => void task(async () => { setUrl(await waveApi.url(a.id)); setPreviewId(a.id) })}>▶</button><button onClick={() => add(a)}>Add</button>{full && <button onClick={() => setEditing(a)}>Edit</button>}</article>)}</div>
 {url && <div className="wave-sfx-preview"><span>{assets.find(a => a.id === previewId)?.name}</span><AudioTransport key={url} url={url} /></div>}
 {editing && <form className="wave-sfx-edit" onSubmit={e => { e.preventDefault(); void task(async () => { setAssets(await waveApi.updateSfx(editing.id, editing.name, editing.category)); setEditing(null) }) }}><label>Sound name<input value={editing.name} onChange={e => setEditing({ ...editing, name: e.target.value })} /></label><label>Category<select value={editing.category} onChange={e => setEditing({ ...editing, category: e.target.value })}>{sfxCategories.map(c => <option key={c}>{c}</option>)}</select></label><button type="submit" disabled={busy}>Save changes</button><button type="button" onClick={() => setEditing(null)}>Cancel</button>{!editing.builtIn && <button type="button" disabled={busy} onClick={() => void task(async () => { setAssets(await waveApi.updateSfx(editing.id, editing.name, editing.category, true)); setEditing(null) })}>Remove from library</button>}</form>}
 {full && legacy.length > 0 && <details><summary>Clips from Sound Studio & Voice Lab ({legacy.length})</summary><p>Copy a saved clip into the SFX library for reuse.</p>{legacy.map(a => <div className="wave-legacy-row" key={a.id}><span>{a.prompt || 'Converted voice'} · {formatWaveTime(a.durationMs)}</span><button disabled={busy} onClick={() => void task(async () => setAssets(await waveApi.addSfx(await waveApi.import('sound', null, a.id), 'Custom')))}>Copy to SFX</button></div>)}</details>}
 </section>
}
