import { useEffect, useState } from 'react'
import { open, save, isDesktop } from '../platform'
import { useWaveStudio } from '../WaveStudioProvider'
import { waveApi } from '../waveStudioNative'
import { errorMessage } from '../native'
import { formatWaveTime, projectDuration, type WaveProject } from '../../../shared/waveStudio'
export function WaveProjectsPanel({onClose}:{onClose:()=>void}):JSX.Element {
 const w=useWaveStudio(),[projects,setProjects]=useState<WaveProject[]>([]),[deleted,setDeleted]=useState<WaveProject[]>([]),[search,setSearch]=useState(''),[trash,setTrash]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 async function refresh():Promise<void>{const [p,d]=await Promise.all([waveApi.list(),waveApi.deleted()]);setProjects(p);setDeleted(d)}
 async function task(fn:()=>Promise<void>):Promise<void>{setBusy(true);setMessage('');try{await fn();await refresh()}catch(e){setMessage(errorMessage(e))}finally{setBusy(false)}}
 useEffect(()=>{void task(async()=>{await w.flush()})},[])
 async function exportBundle():Promise<void>{await w.flush();const p=await waveApi.get(w.project!.id),path=await save({title:'Export project bundle',defaultPath:`${p.name.replace(/[/:]/g,'-')}.wavehs`,filters:[{name:'Homer Wave bundle',extensions:['wavehs']}]});if(path){await waveApi.exportBundle(p,path);setMessage('Project, media and voice references exported.')}}
 async function openBundle():Promise<void>{const path=await open({title:'Open project bundle',multiple:false,filters:[{name:'Homer Wave bundle',extensions:['wavehs']}]});if(typeof path==='string'){await w.flush();const p=await waveApi.importBundle(path);await w.open(p.id);onClose()}}
 const shown=(trash?deleted:projects).filter(p=>p.name.toLocaleLowerCase().includes(search.toLocaleLowerCase()))
 return <section className="wave-dialog wave-projects-panel" role="dialog" aria-modal="true" aria-label="Wave projects">
 <header><div><small>YOUR WORKSPACE</small><h2>Wave projects</h2></div><button aria-label="Close projects" disabled={busy} onClick={onClose}>✕</button></header>
 <div className="wave-project-actions"><button disabled={busy} className="primary" onClick={()=>void task(async()=>{await w.create();onClose()})}>New project</button><button disabled={busy||!w.project} onClick={()=>void task(async()=>{await w.flush();setMessage('Project saved.')})}>Save current</button>
 {isDesktop()&&<><button disabled={busy||!w.project} onClick={()=>void task(async()=>{await w.flush();const p=await waveApi.get(w.project!.id),path=await save({title:'Save portable project folder',defaultPath:`${p.name.replace(/[/:]/g,'-')}.homer-wave`});if(path){await waveApi.saveCopy(p,path);setMessage('Project and media saved together.')}})}>Save copy…</button><button disabled={busy} onClick={()=>void task(async()=>{const folder=await open({title:'Open saved Wave project folder',directory:true,multiple:false});if(typeof folder==='string'){await w.flush();const p=await waveApi.openCopy(folder);await w.open(p.id);onClose()}})}>Open folder…</button></>}
 <button disabled={busy||!w.project} onClick={()=>void task(exportBundle)}>Export .wavehs…</button><button disabled={busy} onClick={()=>void task(openBundle)}>Open .wavehs…</button></div>
 <input className="wave-project-search" type="search" aria-label="Search Wave projects" placeholder="Search projects…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="wave-project-tabs"><button aria-pressed={!trash} onClick={()=>setTrash(false)}>Projects · {projects.length}</button><button aria-pressed={trash} onClick={()=>setTrash(true)}>Recently deleted · {deleted.length}</button></div>{message&&<p role="status">{message}</p>}
 <div className="wave-project-list">{!shown.length&&<p className="wave-project-no-results">{search?'No projects match your search.':trash?'No deleted projects.':'Create a project to start recording or importing audio.'}</p>}{shown.map(p=><article className={`wave-project-row ${p.id===w.project?.id?'current':''}`} key={p.id}><div><strong>{p.name}</strong><small>{formatWaveTime(projectDuration(p))} · {new Date(p.updatedAtMs).toLocaleDateString()} {p.id===w.project?.id?'· Current':''}</small></div>{trash?<button disabled={busy} onClick={()=>void task(()=>waveApi.delete(p.id,true))}>Restore</button>:<><button disabled={busy} onClick={()=>void task(async()=>{await w.open(p.id);onClose()})}>Open</button><button disabled={busy} aria-label={`Delete ${p.name}`} onClick={()=>void task(()=>w.deleteProject(p.id))}>Delete</button></>}</article>)}</div><footer>Projects save automatically. Deleted projects and their media can be restored.</footer></section>
}
